apiVersion: v1
kind: Service
metadata:
  name: manga-scraper-internal
  namespace: private-endpoints
  annotations:
    tailscale.com/hostname: manga-scraper-internal
    tailscale.com/tags: tag:service
    external-dns.alpha.kubernetes.io/hostname: manga-scraper.internal.thetillhoff.de
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: manga-scraper-proxy
  ports:
    - name: https
      port: 443
      targetPort: 8443
