apiVersion: v1
kind: Service
metadata:
  name: trading-internal
  namespace: private-endpoints
  annotations:
    tailscale.com/hostname: trading-internal
    tailscale.com/tags: tag:service
    external-dns.alpha.kubernetes.io/hostname: trading.internal.thetillhoff.de
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: trading-proxy
  ports:
    - name: https
      port: 443
      targetPort: 8443
