#ENC[AES256_GCM,data:yukx6xY6a8OnwQYITtfz+WvEPLAlqQQ4gUtbgGie0q6gHRWOhDcNZCkS+OOihVrkg1yIH6pPxc66s021cy43XQ==,iv:kaNHG1Jh8kVa6opT7q6db/vzWhaOfXlReAogjqWa73g=,tag:Br0/BJG91d83KKK4OVEx+A==,type:comment]
#
#ENC[AES256_GCM,data:cLlqA1+DIiFAtpzJDy4=,iv:dFSDD7vjqj7RBAho3DaxHhwi6jPIg/9OqpFVadxL4Kk=,tag:vk4b0nSCOAH5hL0VpueTfg==,type:comment]
#ENC[AES256_GCM,data:K9qSAfQaGk9+ej4XUe/bw3wN43USkEqxuQeb14EHkHb3/bU2EgtUqO4dcIA6x5FLuskA74jTJLK/Gb0Cg7mLYnaE8IbjrmJwJ10=,iv:6YIUR4ZLOo6sbbO2+BO0K93KzuTaLYqwiDal8sxQH4Q=,tag:Mzt80ZW+D7MAdEeQgP2IQw==,type:comment]
#ENC[AES256_GCM,data:lBK348sUwNjbwBJGv7W9MHEUrC9Mfo9OQIGDAhUa9uKFJZc5TxMcuEwAJAmYMn91G+LDovFhMNWumEHD,iv:6bylBxsk9o/Vd8OHqScqYdPWFpl3LVyZpKD9uVAQvfc=,tag:grXyS8rJM6o78SpU5JdmuQ==,type:comment]
#ENC[AES256_GCM,data:UsWwxEYgCZwGLJ/PetMpLblZ+XclWmtFbZD1STjx+Rw3F5jVelBtKSgISuA/lr9U61jlrLbQJ+DoNbgXryzR+TJQsRyHaAU=,iv:R99PcKyvIiqTQm68/BhGVkt/8glhmBeOm6PnJXJh2VY=,tag:7x8DfjmUZ7ulUaSnDtZxbQ==,type:comment]
#ENC[AES256_GCM,data:jEKNVnsdOTBChx2BKJbhHmSp2qCy7lAuuW0fUL1G49QOKz+tskqmxvbnOg7wLBzeSs7Sx+4lFEw=,iv:6PB4q13xNox+ggWXmaTtqfy0YlJFGPFKPJtBcnMlgvM=,tag:5ug8ngH2xHQKwgGsD65dAg==,type:comment]
#ENC[AES256_GCM,data:HuMHCJSYxd6wJvOPNHgCe8ZZmHNSEUU+nVdQH7gOctZHnI89wVaRcG3SuzLTtpfHPXn2D6jvJsOIfcK92qfssM6AnVhZZ6jHSpLswQ==,iv:FX+RI2t6wLo9/fv+YxezbBOEPAQIeM7Uw5YBOx0ieWA=,tag:LatpkyhbUiFa076BZPfXZQ==,type:comment]
#ENC[AES256_GCM,data:Q9QhFbeVbeTkjKZXLgdv9JLXa35VzRIAYceRx5Q3NmPhQcnOr4Tt9Sq633QosO2m5KIuVbprGN6dYth6ySZS,iv:cuLdAYd8v55QWDNCvIFqftm2dMQ3kpAvEFQC1sIVtxg=,tag:wm6aeYVvJLwx3QNK6gIk1Q==,type:comment]
#ENC[AES256_GCM,data:gCduh+b0cHHeEdCVP8UxV2CpFk6rHUcXYtA4tRHueu9+pakJRXcJgQONnw7mFqtYcEvP/QEmCUR+h3E7JYsZUfsGYncqHgGPtKqZX/3B9w==,iv:nEgFDfrOCF81j1S5tnbb/pXnbfDhxop9ZKdKDWWZhVQ=,tag:NtYPeLda10iQPtdZU+oZwA==,type:comment]
#
#ENC[AES256_GCM,data:nFg9LhDt4LyjHdd1GDP0Ftsclgb67/atxv6IJY2uchQfZNvlDHYiKvXnVA/2+I8J7wYoUyvzkWvRZkHkcViNgKL+Fd8=,iv:BM+wRAVIl7iWfiCN+YAgXcFCt9Sim/Q46Su54h3JCC0=,tag:k9Zt1iIHt5Qe5AkcBkgRmw==,type:comment]
#ENC[AES256_GCM,data:yoeAWMZJQkoqB08Y33MAkbjAFJV49fVf5hO1beYV9QjdzLeYugogC26rv3dWzT6/DsPiNQoo2SBdS/sDnvjao3lfeHcCP7RPchCexbKT+rAkLmM=,iv:jPYVMF6sNRRyUNbSVGhfGPgMEmrbV8Q4CO3nCfLYspk=,tag:75G/Ev8yENMaJzaAKzM+wQ==,type:comment]
#ENC[AES256_GCM,data:XkEMUBQnC992fv4bYOM0Qvt2GGfD8V9I15P6luOocA==,iv:78OutfzCimswZKUJ7kUpxhi7+Is7GfpMS21jMjsE1KY=,tag:yKJ+c/V3EEJaPeXov6qpnA==,type:comment]
tailscale_authkey: ENC[AES256_GCM,data:m22i16i4nBUAd3IfJ67RUISkkyjo,iv:eRpd79GdCwyHdxetzvXpXuX8JYU1KytWOgI8aYzLs7M=,tag:l9milJg0G7RHNmL2V6EbMA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdEQ3aitvSVJuVmM5di82
            d3dyYjlYOGlQQWdwYTdMR2l3cVdVanBpbmlRClJGMmxTRkFnWHl0c1NreVRCSHRt
            M2F6WVRhQm03S0FmckpzVU1ic3NkbmMKLS0tIENnSUxhTm4vSzdjUXgyblozMElX
            K0Z2dytLQUpWOW1IamtnNnJpM1BGZ3MKVP8LvQdgC03Vw0HS9rnYZ1vmA7/Bs6oE
            aaId1iF4vZh1JjwM46r9RwLUKlR6I3PEexUqSkpoJuQ1jwAfAh7PDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1068jmwnqrpg6g2m9aswfwz37fjg7vpwtz5vnxlkcwvf3ed8hjaxsycmf85
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbmdYeGZabnJaSzlkRHpX
            Nm1aUHdVekxIWWR2cVVuOEVmeWNMVDd3YmlzClMzb0xqaUYvQTlNcWZ5UkxCME5M
            YWFzamxPOC9vZEtuSlhWMUFhTzRzREUKLS0tIHFnb2YzRGp1MmdmUytydFRkN1BQ
            eXNJZExuMGorUDlOYXdCbkRORkFSbWsKadUcmn6IcB8fhnPqcxgLWwb2LGVS3QIU
            alKPpcUY6ZCFbbq7fR9StptHior/wz0taC6F6UQpCIXbjj4zhnSYUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jmznk7lwandq9d7mm6fq69uwpa7hf79p6h6qztz0e20wj2yw2a8qylelvw
    lastmodified: "2026-07-07T19:38:25Z"
    mac: ENC[AES256_GCM,data:j0od2fr0avNq9n6Bsay9+DQ5JWiaeGS4WFsYPXCtw3LCiYbyjFAawiFYsvFNo8XfCWIwdOC223ti1AMTW44kacSlqaUI90a8kL+O4tRgIOMcAe0jcM+C9PKle+N8ff3Dc9c9dtaXA0R75+FiMTrz/X+Fn7RagXT7Q2zTFSEKYR0=,iv:ojts/6ea0jpSHHilAwm3eTC2E9tnY/0SYHvtjN4M4OE=,tag:Kw5LonUdazfeAx/NEZFToA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
