apiVersion: v1
kind: Secret
metadata:
    name: manga-scraper-postgres
type: Opaque
stringData:
    user: ENC[AES256_GCM,data:sl65+2Fk/22npnDUlw==,iv:+RiMLOYop0D0LRq7RJ3uL61CQNFUPbyWW4XOgSs7d7g=,tag:xDUIQgNvTsbleF3SrEARhg==,type:str]
    password: ENC[AES256_GCM,data:Zu6TXOT4vo9E66PUhs4eGo1dPYzzqotwnqjeaQ==,iv:gtbLW5+UUgqhJoyVwtRVwcnwOnYT5uZsWs7Wbzv5ZHU=,tag:uLoxIm0U7uC+eF3fzIHk0g==,type:str]
    #ENC[AES256_GCM,data:m8ICs7ozi1utHKZ30zNpXQ5c0PJssnmAyVPuS/KnBlykckcsMHXJnwtts8N+6+K0KvKuyPYyyaIAmGOfgk8HUagJXeczU5T8aGotJwY8rA==,iv:N9FZ6PsyDJiBBFjAR2cyFRJsLU8/yyxVgTUiindb+Qo=,tag:7QnfIHq803F9KhyTBh3RDg==,type:comment]
    #ENC[AES256_GCM,data:tVqD6y/nS7SeIz7R7QXWDfXi2NA8rPQQkE6nF7XqeyCemSqXaaB6hli+Ol2ObjteUI69yk2/dwIqzkkZfPaSXGCf,iv:hnIQh0NCqTfKbwXvqKWbICKh1rtTk09WsGGc7+R1cYA=,tag:fHp/iZowo9gUen3KE+0sCQ==,type:comment]
    url: ENC[AES256_GCM,data:vVcJ6ya/jKAAXSbQDZa4SaYwBWKP6zfLMlbCItJP0kRMOG+BGsLXvsvtHQX5yySd3IgWOEVUWnbHoO3jLp9qYngMZ+L14cGXJfQYa/XWRgKywjcYiFJXgIoWS4dVTjU6hQ==,iv:S+7G/n3oIAuo3ejr8fIWww4I2XV0nkjN5BPhAL+e3QI=,tag:CndTL8jQfCauTFddVyq10A==,type:str]
    dev-url: ENC[AES256_GCM,data:1+K1fhv1CAKYWff9ygzFu7/le1yvWmnkvwy2uI/1hN6ykseiGKTCDTcNXUI+Hf2u8Y6UIBhRIHYWIjWG0OhxHgPJaTZpy51iw5uil36dleyO+TvygVHuURTaZLHh,iv:57f/HO2VvdgQ3eiUakhi3WA7y4UVJU8KDNHFZhr0xE8=,tag:Z4mzdBe18okhn6J8+d9Muw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6c0Z2VDFvZU5SejUreXJP
            WG5kWU5iaTVDck5pTXFXVFlUdDZXb1RWWmlNClY4Um1IMC92VG9YdTE1T3djZHJz
            enZkekUrOS94Nko3N2dYRFZObENUU0UKLS0tIEJMZ2t3VCszTjRTVkRUanhWb1lR
            aDlUbnBEa2w1Zzh5dVNGQmVsSk9JTGcKrIvjem5BmwALVU89ziSUKDomAvo4L1UY
            GPckd7zep7fHe2GAwwXMXPIJLOurSlzgz0EPKnLHAZJmZC1GeU82Lg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1068jmwnqrpg6g2m9aswfwz37fjg7vpwtz5vnxlkcwvf3ed8hjaxsycmf85
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwc3BJSnJYakxRZ0U2eUFt
            L2ZjK2tQNHZZdVhzV1pkUjBPQ0NZVUpWMndjCnZLNUtpSXVDU2wzRDZkL1Q4ZGZS
            RG40TFFjSDdpVWJuaVVrOTdwMTM3UnMKLS0tIFYzbmhNUjk3YmxscXJrM0tvOEdY
            dm5rMGZiY2FrRWxnV3NyWFdMcUNSOTAKBsMr1UoPSc9xW2UmcjhfuX8DZKNsmuxc
            oSEZVhyGNOxwR5iT5V70ob3VMxuVBoPMS39oj4jwJZWcKXB4mlcYiQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jmznk7lwandq9d7mm6fq69uwpa7hf79p6h6qztz0e20wj2yw2a8qylelvw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T22:04:19Z"
    mac: ENC[AES256_GCM,data:0CQR07EakqTZ9bpP0x2TAgGiqHFnmE9L8Ansp9YIH8lScqiDfdnl8KpAVZ5qA5pcT53ph7wUEBwW6nA5ouKzYr/ihaYl5j9J666+DBD7zYOs2OYhiByTzCc5HtI0I9ft2uMIfJLQMkIHj/tVfFUJGZ21tqI10OnURwD0iciwiQo=,iv:B+Kx/a+pCb2bYY7nI+yLwWVWcvW/spcwcCD5EzKIN3I=,tag:EEGUJ7OPDq+cLKVnhkb8Mg==,type:str]
    version: 3.13.2
