apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 74.0.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  interval: 10m

  valuesFrom:
    - kind: ConfigMap # This value is case sensitive
      name: prometheus-helm-values # automatically overridden by kustomize
      # valuesKey: values.yaml # `values.yaml` is the default key
