apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-link-shortener
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/apps/hydra/link-shortener
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
