apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibkr-broker
  namespace: trading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibkr-broker
  template:
    metadata:
      labels:
        app: ibkr-broker
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: ibkr-broker
          image: ghcr.io/thetillhoff/trading-ibkr-broker:103 # {"$imagepolicy": "trading:trading-ibkr-broker"}
          workingDir: /app/broker
          command:
            - "uvicorn"
            - "app:app"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "8002"
          envFrom:
            - secretRef:
                name: trading-ibkr
          env:
            - name: IBKR_HOST
              value: ibkr-gateway
            - name: IBKR_PORT
              value: "4004"
            - name: IBKR_CLIENT_ID
              value: "2"
          ports:
            - containerPort: 8002
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
