apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: trading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: frontend
          image: ghcr.io/thetillhoff/trading-frontend:29 # {"$imagepolicy": "trading:trading-frontend"}
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: trading
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 8080
