apiVersion: v1
data:
  .dockerconfigjson: ENC[AES256_GCM,data:txh0hJBQTuQxZKJGFI4c3HNN3QiTDMOAiXZ6Z0yjRVFiCs0jUB188QBoi9BzUGUUtgQDzTA9KQ8jGmr2W27+i1Zlqf2CimMPlLafPLQBdFJTOVyH4+hr7JU9gm7hZVfa0VxUjMGSiGgmpxHesfSI8ZT2XBrHvZJORFU5thAiywne+pwfiONhj7CHjA/NcqHq6cWsBwTCW7gC1T1eP1V7pAjuKU3ab0Ga6bfu3K+FkaIbV6JudeE6M3Vv0PJMiiLRBk3ex04TJ6MDR9dGYQT0YQxoWKDUzSi2DFgwaEAHGpj6ZBvPdy2kBH9UN3Y741b5RgZg1I8AVZ4=,iv:PXdkMNK/mDFJs7J/dghVObUZIYqcDIt8TrQtodyJtNI=,tag:QifJ0C3onx9d7mD4jY4U6Q==,type:str]
kind: Secret
metadata:
  name: ghcr-creds
type: kubernetes.io/dockerconfigjson
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRmp0Tks4a3puNEltOEhR
        Sk9DMjV0UFNIYURaNTdmbGFqMzhRMXJ3TjBNCjNLQWNvUE5MVUdRTmlXZUc1am01
        TE56alRaZVU0dUYvZmVjMC93S25Lb0EKLS0tIFBaSTMyYndYcHdvTE03bkRiRXpR
        Mkx2WUZjZm9wMUlLR3hKRXJ1VGNDUEEKq2J05WiqPu0uHfJ0P6fFUrhEBH1YAxk7
        rG+6wt953kex5/E30JQ9E76nWB1qm3OXuNpmI+dY/YPVuWl0Svkclg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1068jmwnqrpg6g2m9aswfwz37fjg7vpwtz5vnxlkcwvf3ed8hjaxsycmf85
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0N29QaWlDNE9semhMVThw
        SGtqYTJwb2o0NkRwaEgyVmNNNnJnUzV0d0VJCkdlejJweVI1NktiTGpFWitib0hT
        c3VDVGs3YnE0T3BqcU5naU1CbU5TcDQKLS0tIGZJM29iaUg4T1VyVkRITTE0WFNB
        ODdIWjltTlo5a2t1ZTVTSXhjeWcvZmcKz8yTvmIxqpX9IIdKNOqWzt7p2d+T2WrZ
        OoDPdInuJ44Cm7g4sRKtsP6zA35i/p5ragVM4S+gJOmOiYilXTttKA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1jmznk7lwandq9d7mm6fq69uwpa7hf79p6h6qztz0e20wj2yw2a8qylelvw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-25T23:49:21Z"
  mac: ENC[AES256_GCM,data:dSbxJDrF9PdNTGE9NLDOrqxF+24HvjGmN/Lc/9bJu3FI3w4X+8Ho63y1vQXGvn1iZoc4A4ZQ2csvqkEMki7mYli+peQbCtMKJxoZb8h9qm3YnmRpnQUvEMq2vqhJNXgrCJLVkk5EyagH0t2rZ1mrs6qxqGkHKDeVHYdLo/2pMmI=,iv:Nvchf7ppspvCwvs1VypPBOEIYDgrjPr91SgGSDrveM8=,tag:Zwuu/3rPByDI9mavKbjX8g==,type:str]
  version: 3.13.1
