apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: trading-worker
  namespace: trading
spec:
  imageRepositoryRef:
    name: trading-worker
  filterTags:
    pattern: '^(?P<run>[0-9]+)$'
    extract: '$run'
  policy:
    numerical:
      order: asc
