apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trading
resources:
- namespace.yaml
- ghcr-creds.secret.yaml
- trading-postgres.secret.yaml

- crds.yaml
- rbac.yaml
- serviceAccount-trading-worker.yaml
- role-trading-worker.yaml
- roleBinding-trading-worker.yaml
- storage.pvc.yaml

- postgres.yaml
- backend.yaml
- frontend.yaml
- operator.yaml

- httpRoute-http.yaml
- httpRoute-https.yaml

- imageRepository-backend.yaml
- imageRepository-frontend.yaml
- imageRepository-operator.yaml
- imageRepository-worker.yaml
- imagePolicy-backend.yaml
- imagePolicy-frontend.yaml
- imagePolicy-operator.yaml
- imagePolicy-worker.yaml
- imageUpdateAutomation.yaml
