apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trading-data
  namespace: trading
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
