apiVersion: v1
kind: Secret
metadata:
    name: trading-ibkr
    namespace: trading
type: Opaque
stringData:
    #ENC[AES256_GCM,data:ZZ/5FtJo+dA7cCW04l4qSYJPkfKfoPC51iZSQun1qxkR395ZBkloQgoR4bC/gcajVPBqDuSWtUM1oc+zAoLA0ZGXVdw5HUJS1h3S2IftoFIFquXQKPpAxc7VlPbvSLs=,iv:B7n5dQEWr9DZnVDqu5luO4RY8Xs3Ar2kopyma9pZNGo=,tag:fZdAf3edYQQ4ii/O0FOy6Q==,type:comment]
    TWS_USERID: ENC[AES256_GCM,data:NmaoenjgTtakR8I=,iv:rOEaW0cYntpo6T2NvFfmNg7L6avzOIGJts17Fqj8qjA=,tag:x/R1EQeYWhX1bnv/3/3Law==,type:str]
    TWS_PASSWORD: ENC[AES256_GCM,data:xguLJ8w07lvLVtyCOyNHwC/qtgAu7gRxjkADqWBssD+iBTDTpg==,iv:6T2zF6Os1BkhLhhY47QPsuvOuWnNpvFDnLaqUSeSNGw=,tag:k/rGDYc0UB5WQ9znBdUFbw==,type:str]
    #ENC[AES256_GCM,data:c4sqbe0IlhyF3iDQtnFJ0gNl,iv:p0TekyEmZnhCLmqRx0pELyUE4BDsnKPLjt1q0UNP/Rs=,tag:qHs7jMkO+6psDsL/g0S6vQ==,type:comment]
    TRADING_MODE: ENC[AES256_GCM,data:vjZuQAE=,iv:l1BZj7V9u26mX7eMT/gR0FifR6rdrmu2hnCf4Da6nsM=,tag:I//ht+cKZRlO/EOwZ6s11A==,type:str]
    #ENC[AES256_GCM,data:R1pWwFo3WQS6aMF3Vakc6oXbCitnwOq2R3W36YhvE1WkHXu+dwHN/oUtznm0xgC/tSCPTn3OzuhFi4fArDV0yXFcOizNFnHRjBLUR63M4N8v2IyESAqLrH/wfTOt,iv:Lwih+YuQy26E/7ibPuO916AWT4qSc8FCptx+xwIe5Nc=,tag:VGx1lEn3xuCxaMH0SYEJIw==,type:comment]
    #ENC[AES256_GCM,data:7EwNYGpiKRIcQfqFoYeI6Wyu4fqtWB1WGUws6lrb5w8QRGiN6w==,iv:kQ0cXbbcfVY0mGy2uWBkc8RQlAx/Sm4w5vW+l7r7Ll8=,tag:095QO1FWi1CHuL/07Q9ytw==,type:comment]
    VNC_SERVER_PASSWORD: ""
    READ_ONLY_API: ENC[AES256_GCM,data:364=,iv:ZotygTLRVRxv2XRuxUK4es8Wazs+gTnefInvvxUIVME=,tag:vcWNbd5E/940MRSy79LZPg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbjhZcE02WjRpa3orQk04
            djd0bjEvbURpaElZRmp5MitjMHZ6OXBNQUZzCk0xZk9xTERxSVdFVEdXL2pwQmRB
            emk3eU5uZkNQTk1XUmxxMTRkclY5T3MKLS0tIGM1UWNpOFpMOHRGWEdWbVNWblFN
            ckdKSE43QURGdDFTNWFBUFRPL0RuWGcK8+/+TTffrl3Yj6xYyfv6awyPnBVZ00Wr
            LeuU44AEpvZ4KPY/AWt19K+1cBzh96RNCwoFOP0HW3HFcernjIvgWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1068jmwnqrpg6g2m9aswfwz37fjg7vpwtz5vnxlkcwvf3ed8hjaxsycmf85
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVEhWbTlrSzhWK0VXZ05U
            bnZ4VzBWUFVyMEZIT2Q4OTRxd2NkSlM3M2lJCnRTL3pxMTRXWndNbkt5VkkzQ0ox
            WGFSU1JPRDJlRExRRngycklCUFNnYW8KLS0tIGx5OHpWYVd5OUxYbkIwOUVNSEcv
            UGx5RTVHUlY1RzZXYXp5THRKS2NJYVkK6KK2ytVtWAKYiY5ywu0Stv2W4fB7cfbE
            fpst7u13VdzlW81SxUGWUs7A8ux6aHZmi0vOAe4NNVnzvTztzXWK2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jmznk7lwandq9d7mm6fq69uwpa7hf79p6h6qztz0e20wj2yw2a8qylelvw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-09T11:21:44Z"
    mac: ENC[AES256_GCM,data:YDH86HUtdlL6SKuGEGBaTV7VRJd/VaTAOMEI3BGuuN5G5BLpbZUYm6QmELxVu5n9HE2E0ci0Wq8BqAmZJhH3Vjd8OZt9N7HtyX6vZC7BEQQZA6RnOb5J1WO8WaZHMvqmheryGO6HNYS2Or+cS/KeYz11Aj3aOCOg8Kg+w7kGEnw=,iv:hudNHC1JINjFyUWCN0luX64c/bVz7WbiGsJ3iX5huvg=,tag:AAjNqxV/Fwq1eyXHNfWU6A==,type:str]
    version: 3.13.2
