apiVersion: v1
kind: Secret
metadata:
  name: trading-ibkr
  namespace: trading
type: Opaque
stringData:
  IBKR_USERNAME: ENC[AES256_GCM,data:0PwBTMDMT/fpx6g=,iv:4T6i0E6NGU+JukrsNPZJ8wcduwiXyeGyj2F995LeaBc=,tag:usC6yFWpUtsZaHkYCyE9uA==,type:str]
  IBKR_PASSWORD: ENC[AES256_GCM,data:k5XO+6PHMdWpA0RK+ltwaoywkUSej6ZFT5S1xdcoLDxEK8S4vQ==,iv:hQ9+RJ0g7U8kN1kZtoPyCiYPuE9ZcrgIe4+WSCZ15WQ=,tag:JmhqjtoCOCbI4f2ahVev+g==,type:str]
  TRADING_MODE: ENC[AES256_GCM,data:vjZuQAE=,iv:l1BZj7V9u26mX7eMT/gR0FifR6rdrmu2hnCf4Da6nsM=,tag:I//ht+cKZRlO/EOwZ6s11A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbjhZcE02WjRpa3orQk04
        djd0bjEvbURpaElZRmp5MitjMHZ6OXBNQUZzCk0xZk9xTERxSVdFVEdXL2pwQmRB
        emk3eU5uZkNQTk1XUmxxMTRkclY5T3MKLS0tIGM1UWNpOFpMOHRGWEdWbVNWblFN
        ckdKSE43QURGdDFTNWFBUFRPL0RuWGcK8+/+TTffrl3Yj6xYyfv6awyPnBVZ00Wr
        LeuU44AEpvZ4KPY/AWt19K+1cBzh96RNCwoFOP0HW3HFcernjIvgWg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1068jmwnqrpg6g2m9aswfwz37fjg7vpwtz5vnxlkcwvf3ed8hjaxsycmf85
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVEhWbTlrSzhWK0VXZ05U
        bnZ4VzBWUFVyMEZIT2Q4OTRxd2NkSlM3M2lJCnRTL3pxMTRXWndNbkt5VkkzQ0ox
        WGFSU1JPRDJlRExRRngycklCUFNnYW8KLS0tIGx5OHpWYVd5OUxYbkIwOUVNSEcv
        UGx5RTVHUlY1RzZXYXp5THRKS2NJYVkK6KK2ytVtWAKYiY5ywu0Stv2W4fB7cfbE
        fpst7u13VdzlW81SxUGWUs7A8ux6aHZmi0vOAe4NNVnzvTztzXWK2Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1jmznk7lwandq9d7mm6fq69uwpa7hf79p6h6qztz0e20wj2yw2a8qylelvw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-04T09:07:41Z"
  mac: ENC[AES256_GCM,data:+VPduD4JYA0OloodQAOhX70VLu9sMIciRo0NBRsI045urHNDGn7Sdjov5rVYB9RgxDiqvCd82KV27mAS+Ju04GDYicC2/C/277LCAoWZsAIPlAPKdYFLAvo1pfxeBRm0GNj73Q+Xl6dSKpL877D/4scLfXXj5ZLcfL6IXOCn0Xw=,iv:hloAZ7WcreiViRYdIx6JFYy5WGbzITRPZmhap6yE8Fg=,tag:aeWEoVgHRw6ek1jB93qk7Q==,type:str]
  version: 3.13.2
