# https://taskfile.dev

version: '3'
silent: true

tasks:
  build:
    desc: "Build hcloud image for talos. Example usage: task build ARCH=amd64"
    dir: 'packer'
    vars:
      HCLOUD_TOKEN:
        sh: 'cd {{.TASKFILE_DIR}}/pulumi && pulumi config get hcloud:token 2>/dev/null'
    cmds:
      - |
        docker run --rm \
        --entrypoint=/bin/sh \
        -v $(pwd):/packer:z \
        -w /packer \
        docker.io/hashicorp/packer:light-1.15.1 \
        -c \
        "export PKR_VAR_HCLOUD_TOKEN={{ .HCLOUD_TOKEN }} && packer init . && packer build -var-file=common.pkrvars.hcl -var-file={{ .ARCH }}.pkrvars.hcl talos-on-hcloud.pkr.hcl"
    requires:
      vars:
        - name: ARCH
          enum: [amd64, arm64]

  deploy:
    desc: "Deploy pulumi stack. Example usage: task deploy"
    dir: 'pulumi'
    cmds:
      # keep node_modules in sync with package.json (esp. after provider bumps)
      - npm install
      - pulumi up

  configure-files:
    desc: "Configure talosconfig and kubeconfig. Usage: task configure-files"
    dir: 'pulumi'
    generates:
      - './talosconfig'
      - './kubeconfig'
    cmds:
      - pulumi stack output --show-secrets talosconfig > talosconfig
      - pulumi stack output --show-secrets kubeconfig > kubeconfig

  configure-env:
    desc: "Configure talosconfig and kubeconfig env vars. Usage: task configure-env | source /dev/stdin"
    cmds:
      - |
        echo export TALOSCONFIG="$(pwd)/pulumi/talosconfig"
        echo export KUBECONFIG="$(pwd)/pulumi/kubeconfig"
        echo export SOPS_AGE_KEY_FILE="$(pwd)/age.key"

  reconcile:
    desc: Reconcile flux sources
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - flux reconcile kustomization flux-system --with-source
      - flux reconcile kustomization infrastructure-controllers --with-source
      # resources (depend on controllers)
      - flux reconcile kustomization resource-cert-manager --with-source
      - flux reconcile kustomization resource-discord-notifications --with-source
      - flux reconcile kustomization resource-firewall --with-source
      - flux reconcile kustomization resource-gateways --with-source
      - flux reconcile kustomization resource-monitoring --with-source
      - flux reconcile kustomization resource-private-endpoints --with-source
      # apps
      - flux reconcile kustomization app-link-shortener --with-source
      - flux reconcile kustomization app-thetillhoff-de --with-source
      - flux reconcile kustomization app-trading --with-source
      - flux reconcile kustomization app-umami --with-source
      - flux reconcile kustomization app-vaultwarden --with-source
      - flux reconcile kustomization app-webscan --with-source
      - flux reconcile kustomization app-wedding-website --with-source

  flux-status:
    desc: Show flux status
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - flux status # ?

  delete-nodes:
    desc: |
      Delete nodes from k8s prior to deleting servers. Example usage: `task delete-nodes --dry -- <nodename1> <nodename2>`
    dir: '{{ .USER_WORKING_DIR }}'
    prompt:
      - This will remove the nodes '{{ .CLI_ARGS }}' from the cluster... Do you want to continue?
      - Sometimes, the `talosctl reset` command hangs. Use `Ctrl+C` to abort and continue after veryfing it was shutdown.
    cmds:
      - for:
          var: CLI_ARGS
        cmd: kubectl cordon '{{ .ITEM }}'
      - for:
          var: CLI_ARGS
        task: delete-node
        vars:
          CLI_ARGS: '{{ .ITEM }}'

  delete-node:
    internal: true # Not listed by `task -l`
    desc: |
      Delete node from k8s prior to deleting hcloud server. Example usage: `task delete-node --dry -- <nodename>`
    dir: '{{ .USER_WORKING_DIR }}'
    preconditions:
      - msg: 'Node not found'
        sh: kubectl get node '{{ .NODE_NAME }}'
      - msg: 'kubeconfig not set'
        sh: kubectl version
      - msg: 'talosconfig not set'
        sh: talosctl version -n '{{ .NODE_IP }}'
    cmds:
      - |
        kubectl drain '{{ .NODE_NAME }}' --ignore-daemonsets --delete-emptydir-data
        talosctl -n '{{ .NODE_IP }}' reset --system-labels-to-wipe STATE --system-labels-to-wipe EPHEMERAL --wait=false
        kubectl delete node '{{ .NODE_NAME }}'
        echo 'You can shutdown the server now.'
    vars:
      NODE_NAME: '{{ .CLI_ARGS }}'
      NODE_IP:
        sh: kubectl get nodes -owide | grep {{ .NODE_NAME }} | awk '{print $6}'

  upgrade-k8s:
    desc: |
      Upgrade k8s to the specified version. Example usage: `task upgrade-k8s -- 1.33.0`
    dir: '{{ .USER_WORKING_DIR }}'
    preconditions:
      - msg: 'kubeconfig not set'
        sh: kubectl version
      - msg: 'talosconfig not set or node not reachable'
        sh: talosctl version -n '{{ .NODE_IP }}'
    cmds:
      - |
        talosctl upgrade-k8s \
        -n '{{ .NODE_IP }}' \
        --to '{{ .K8S_VERSION }}' \
        --with-docs=false \
        --with-examples=false
    vars:
      K8S_VERSION: '{{ .CLI_ARGS }}'
      NODE_IP: # Need a random controlplane node to trigger the upgrade from
        sh: kubectl get nodes -owide --no-headers | head -n1 | awk '{print $6}'
