apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- statefulset-mariadb.yaml
- service-mariadb.yaml
- statefulset-umami.yaml
- service-umami.yaml
- ingress.yaml
- mariadb.secret.yaml
- umami.secret.yaml
