apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/ingress-nginx
- ../base/cert-manager
#- ../base/grafana
- thetillhoff
- vaultwarden
- link-shortener
- umami
#- pihole
#- global-tcp-udp-services.yaml
