apiVersion: v1
kind: Secret
metadata:
    name: test
data: ENC[AES256_GCM,data:AezM2qRjXg+TPMT9IFSz,iv:8J8qc6vd3VH7BYX77rZz5laGmWm9JXTV6BEKdAo/+dE=,tag:wmEb82OS0EluGk2RnMXc7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jmznk7lwandq9d7mm6fq69uwpa7hf79p6h6qztz0e20wj2yw2a8qylelvw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhS2FVNUVsamlKbU1xL1Az
            RS93N0dFcmpwaDQyUFB1a2ZGbkJkMHpBZlRBCkhWc2hWS1ZJVHdFMUtEbU1EM0hx
            eXJlWHJ6aE93Q1p0ZmJPMjFxVHVlUGsKLS0tIHVFbmRKWWhoOWRIb0xhTjVMQVlQ
            YnRyVUlFZlo4VnJlaXZkd2lreC9MWXcKzxhcE8IDTkdV75GMQiUCFLRDqjqCNpSc
            JKGMxZW+M7cShmqYyc6jjXYq7k4R1vhd6am+Wx2rqWOk5t0tlmlEgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-06T21:26:35Z"
    mac: ENC[AES256_GCM,data:GORgUjBf3q+CJrwAaOJv7MHA/Escv06qpHQpGW6ZCr9czs8ft67Hz9awa6YGLiwtgcxxMFkc0+RcfTI/bGEXX8qoCKH9/JRjEU92OMHImXuziGGd+rLa/64puiNuCh9XmFfIPjV3a0UtTeTDDV4+YSYRnIhn5xnnI/CeiQ2xiug=,iv:Y9hjbCXZ1Pn7AX3DVZlxu1zpK5Hwnnkn+VH5AudRY4U=,tag:jiGpy+6icvvS6KX3rka5jg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
