apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
spec:
  chart:
    spec:
      chart: tailscale-operator
      sourceRef:
        kind: HelmRepository
        name: tailscale
      version: v1.88.4
  interval: 10m

  valuesFrom:
    - kind: ConfigMap # This value is case sensitive
      name: tailscale-helm-values # automatically overridden by kustomize
      # valuesKey: values.yaml # `values.yaml` is the default key
