apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailscale
resources:
- namespace.yaml
- operator-oauth.secret.yaml
- helmRepository.yaml
- helmRelease.yaml

configMapGenerator:
- name: tailscale-helm-values
  files:
  - values.yaml

configurations:
- kustomizeconfig.yaml # Used to map the generated configmap into the helmRelease
