apiVersion: apps/v1
kind: Deployment
metadata:
  name: webscan
spec:
  selector:
    matchLabels:
      app: webscan
  replicas: 1
  template:
    metadata:
      labels:
        app: webscan
      annotations:
        kubernetes.io/egress-bandwidth: "10M"
        kubernetes.io/ingress-bandwidth: "5M"
    spec:
      containers:
      - name: webscan
        image: ghcr.io/thetillhoff/webscan:5.2.1 # {"$imagepolicy": "webscan:webscan"}
        ports:
        - containerPort: 8080
        args:
        - --port=8080
        - --redis-addr=redis:6379
        - --max-concurrent-scans=2
        - --max-queue-size=50
        - --scan-timeout=30s
        - --timeout=5s
        env:
        - name: DOMAIN_BLOCKLIST
          value: |
            cluster.local
            svc.cluster.local
        - name: IP_BLOCKLIST
          value: |
            127.0.0.0/8
            10.0.0.0/8
            172.16.0.0/12
            192.168.0.0/16
            100.64.0.0/10
            169.254.0.0/16
            ::1/128
            fc00::/7
            fe80::/10
        livenessProbe:
          httpGet:
            port: 8080
          initialDelaySeconds: 5
