apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: webscan
resources:
- namespace.yaml
- deployment-webscan.yaml
- deployment-redis.yaml
- service-webscan.yaml
- service-redis.yaml
- httpRoute-http.yaml
- httpRoute-https.yaml

- imageRepository-webscan.yaml
- imagePolicy-webscan.yaml
- imageRepository-redis.yaml
- imagePolicy-redis.yaml
- imageUpdateAutomation.yaml
