apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: thetillhoff-de
spec:
  parentRefs:
  - name: http-gateway
    namespace: gateways
  - name: https-gateway-thetillhoff-de
    namespace: gateways
  hostnames:
  - dev.thetillhoff.de
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    filters:
    - type: ResponseHeaderModifier
      responseHeaderModifier:
        remove:
        - server
    backendRefs:
    - name: thetillhoff-de
      port: 80
