apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: https-gateway-thetillhoff-de
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  gatewayClassName: cilium
  listeners:
    - name: thetillhoff-de
      hostname: thetillhoff.de
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: thetillhoff-de-tls-certificate
    - name: link-thetillhoff-de
      hostname: "link.thetillhoff.de"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: thetillhoff-de-tls-certificate
