apiVersion: v1
kind: Secret
metadata:
    name: backup-secret
    namespace: longhorn
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:AiA1FOCWJ7FMSLouzBtNwvmnjtc08cax7g==,iv:/7aq5Nz8Zq7uhnfeeygMtl9TjDVzJOBrBJs/aIH7TQk=,tag:m7k0m8MLNObYgxMNlxXdZQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:C770nZs6sP6rWiqX0qSXyBTf7F7hk/xq+tIvFRocLg==,iv:U9Ftke+QzXfTafOW9gKSfVAxawWZs5H5EBgQNMPP3GI=,tag:Ecronnth5NI2JJe9uYEdnQ==,type:str]
sops:
    age:
        - recipient: age1068jmwnqrpg6g2m9aswfwz37fjg7vpwtz5vnxlkcwvf3ed8hjaxsycmf85
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bVZvREYvTnI4bTZzWUFO
            NWhybVA5Tm91RzFNTUJaVGZwWm0vVWo2QkFrCmkxU1A2MGFlZWluMnNaNDQzc1U4
            S1A4RlY4ektYbnRoeHE2WjhuVjMyd00KLS0tIE5tNlN0bjJlQ2M4R1VpMTlzK21h
            VUxIL3U4N1ZMbHhGbE5ROWtWT0U1M0kKDuqul/3lUwdd5CgbyZDpv7tSaGlB66Wh
            SM1KEB5twqsyyfbWz2eVEtzqlNkB14QOoTYMJL/CIyU7WNgwpcjWOA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jmznk7lwandq9d7mm6fq69uwpa7hf79p6h6qztz0e20wj2yw2a8qylelvw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNmQwdjN6SFN1dVNXdUFV
            V0gxUHVCekgxYWJzWitPd2ZvcmJ0MEtha1dvCitJWGpVS21WbFJPeXJ1eE1RWWdM
            bmkrZml3bm5Pc0pUUDkrNWlDdDVuaDAKLS0tIFVDYjlRSVJFUFJDYUlEY2JGRU80
            WW9mZytIMWZjQzFqa1FjUWI4S3JFUEUKTkqNdz1uE+BpmGLgKp8xgp42wFRvdZ7v
            mcxTz3J7SUeRfyiAjBMrAMFXAlBd1XUdpxVHMQ0tFbncXvoEhWttQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T01:52:48Z"
    mac: ENC[AES256_GCM,data:Wq6fSveaFL95FJanZ8HsobpDd+Sv22tDp8kd7x2CSBryw07u5IOZmZjo+v5OjvrP1GH7i8osow5d10d/PACooQYby7u09Rop3YPdYK9/ofSiJd4d/q+tgX2DNJqToeXlm7c/4XGgC7FGH8GVfy/2MiVLMgkad3xYP5gwwfejh6I=,iv:uZ5hbs4/fx6YtuVEMf1DImC6xVf7y8fOH6Nrt4YlSJA=,tag:X5kMPOrr4VJg5w4sQJE1wA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
