apiVersion: v1
kind: Secret
metadata:
    name: backup-secret
    namespace: longhorn
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:4/shJ2G2KCuhRsdOWkhQgIsdkaofefYA8g==,iv:hXWMFUYX2U1QLWIQStDLmvpNWxh97P1rKHAc1rX1ckk=,tag:AjPzfoRWtf2DemDQM3zuwQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:itGzUGLwL2YSegWm1/CTh3eXhOWL6p+hevbMNpYCMg==,iv:OYzAr4Xj6v4w3WUXtXVKtOyICFtN+qOPrDTIhFlbuZU=,tag:Xx+MFnNewEiZlmBpb0+M8A==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:MRyJINSte0KiC1H2NI07JxPCPETSE50a8wbU2jySPZcphJlrGtVjoYA=,iv:Dj7DMlInfBy9qQ4YFsiTmDKZJliVRxFSOXM7pKdfRc4=,tag:Sxqkt6SDVS4w6nnJV+Kmjg==,type:str]
sops:
    age:
        - recipient: age1068jmwnqrpg6g2m9aswfwz37fjg7vpwtz5vnxlkcwvf3ed8hjaxsycmf85
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bVZvREYvTnI4bTZzWUFO
            NWhybVA5Tm91RzFNTUJaVGZwWm0vVWo2QkFrCmkxU1A2MGFlZWluMnNaNDQzc1U4
            S1A4RlY4ektYbnRoeHE2WjhuVjMyd00KLS0tIE5tNlN0bjJlQ2M4R1VpMTlzK21h
            VUxIL3U4N1ZMbHhGbE5ROWtWT0U1M0kKDuqul/3lUwdd5CgbyZDpv7tSaGlB66Wh
            SM1KEB5twqsyyfbWz2eVEtzqlNkB14QOoTYMJL/CIyU7WNgwpcjWOA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jmznk7lwandq9d7mm6fq69uwpa7hf79p6h6qztz0e20wj2yw2a8qylelvw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNmQwdjN6SFN1dVNXdUFV
            V0gxUHVCekgxYWJzWitPd2ZvcmJ0MEtha1dvCitJWGpVS21WbFJPeXJ1eE1RWWdM
            bmkrZml3bm5Pc0pUUDkrNWlDdDVuaDAKLS0tIFVDYjlRSVJFUFJDYUlEY2JGRU80
            WW9mZytIMWZjQzFqa1FjUWI4S3JFUEUKTkqNdz1uE+BpmGLgKp8xgp42wFRvdZ7v
            mcxTz3J7SUeRfyiAjBMrAMFXAlBd1XUdpxVHMQ0tFbncXvoEhWttQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T02:47:27Z"
    mac: ENC[AES256_GCM,data:MbaSpvDnb8YC4oSz2/JZSaeCNBQyL8TVgeHoLoRw1VO4Fk5e8S6bNLGoAuRuZIRp2rowGjdmvpacAhozoEpaNXHVV2CSjhtbuVmigx5/HhYHofbbizfF9BtNyIp3q0rWua4xI0Td7SnDeS4VESfycmYiyrsWhKSimV8rzqNvLPA=,iv:d7xKUO87D5Ar8M29FchMJhRJFf5BmtqJ6ES5eSJU+cI=,tag:ai5lD7cRE9xpexIzgJ+LFw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
