apiVersion: v1
kind: Secret
metadata:
    name: backup-secret
    namespace: longhorn
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:4/shJ2G2KCuhRsdOWkhQgIsdkaofefYA8g==,iv:hXWMFUYX2U1QLWIQStDLmvpNWxh97P1rKHAc1rX1ckk=,tag:AjPzfoRWtf2DemDQM3zuwQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:itGzUGLwL2YSegWm1/CTh3eXhOWL6p+hevbMNpYCMg==,iv:OYzAr4Xj6v4w3WUXtXVKtOyICFtN+qOPrDTIhFlbuZU=,tag:Xx+MFnNewEiZlmBpb0+M8A==,type:str]
sops:
    age:
        - recipient: age1068jmwnqrpg6g2m9aswfwz37fjg7vpwtz5vnxlkcwvf3ed8hjaxsycmf85
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bVZvREYvTnI4bTZzWUFO
            NWhybVA5Tm91RzFNTUJaVGZwWm0vVWo2QkFrCmkxU1A2MGFlZWluMnNaNDQzc1U4
            S1A4RlY4ektYbnRoeHE2WjhuVjMyd00KLS0tIE5tNlN0bjJlQ2M4R1VpMTlzK21h
            VUxIL3U4N1ZMbHhGbE5ROWtWT0U1M0kKDuqul/3lUwdd5CgbyZDpv7tSaGlB66Wh
            SM1KEB5twqsyyfbWz2eVEtzqlNkB14QOoTYMJL/CIyU7WNgwpcjWOA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jmznk7lwandq9d7mm6fq69uwpa7hf79p6h6qztz0e20wj2yw2a8qylelvw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNmQwdjN6SFN1dVNXdUFV
            V0gxUHVCekgxYWJzWitPd2ZvcmJ0MEtha1dvCitJWGpVS21WbFJPeXJ1eE1RWWdM
            bmkrZml3bm5Pc0pUUDkrNWlDdDVuaDAKLS0tIFVDYjlRSVJFUFJDYUlEY2JGRU80
            WW9mZytIMWZjQzFqa1FjUWI4S3JFUEUKTkqNdz1uE+BpmGLgKp8xgp42wFRvdZ7v
            mcxTz3J7SUeRfyiAjBMrAMFXAlBd1XUdpxVHMQ0tFbncXvoEhWttQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T02:17:23Z"
    mac: ENC[AES256_GCM,data:BxnoXAAnZA3Oxv0r+Ico9zzHED3TKF9EmYIXbvtCsKW+B9R+anFo119aOHG6pSKcULQeVbf2RmwOaXY8Gl9uHIhbqR6HbWwH+Sny5cSFBC+CO6CnSou+mvRKQ+Jq/YSN6aGBxT7fk8Z7aaIW5O2JpbyKfimZ7R2oW2PoJknNOvQ=,iv:ToBdGwUwDeFFkpNd3NVygBPbSaYkrQ/WPvIh0dX3WAc=,tag:yaMr0GQyFcgutWeE3vkPEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
