apiVersion: v1
kind: Secret
metadata:
    name: longhorn-crypto
    namespace: longhorn-system
stringData:
    CRYPTO_KEY_VALUE: ENC[AES256_GCM,data:WdPxQ+SuyMKP6nBf0qTGRYCUwNwYXt9jYncsX2ouScikAqcgEuWUiF2ORIQ=,iv:eoBR/8QVGtUnUuJIPaPe41VWfWKwx/czb4gCGiurMhM=,tag:RfgO2MHbD08rcpPyEoDEjA==,type:str]
sops:
    age:
        - recipient: age1068jmwnqrpg6g2m9aswfwz37fjg7vpwtz5vnxlkcwvf3ed8hjaxsycmf85
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUFYrOFBic1oxSWZwT0RZ
            ejM5VTljTDdxVE9RTGhEUXE3RUMwcGYra0NzCldLcmFpTUtlVHJFaE1kL2Rqbzg3
            dXRQZExWcmNpUERJcm5TUUpBc0FkaWsKLS0tIEVZN2JORFhCT0NFY0lNUW03WDkv
            YTNSd2Z0R3V3L3JaZElXeDNhbTdILzgKy/8t46oEc0gaq9jOntqiHuFdmaQEaaXE
            2DSH8P4PV59YmgcowKfPmA9zGzXbLmGE2xVpb34ed9+WpFzV2uF/yA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jmznk7lwandq9d7mm6fq69uwpa7hf79p6h6qztz0e20wj2yw2a8qylelvw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbG0rQjRJemZzdzlIUDR4
            MkZ3czdXcTF6RjRIdWRqN1BHZ0U1K2RHZEZJCmtaQlhaN3NrUGFlVC9yQmhTN3ll
            UG5SU1NaNXpPVGtsWGE5UTZQZ0VhZlEKLS0tIG1lQlpraUU3VnNOR3FpK29sd3Nt
            VmNwdDdXMTBkR0FsNklKZ2R6K21MT0kKfb2er5jpBh+itxH1zi1GwJVkI/Zcf5Jd
            bMKYUbzSZfOnS88g7cxGKvJd0wi+1N2i+tSxHpPienQ/Xphvv5Ovmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T01:55:59Z"
    mac: ENC[AES256_GCM,data:DoY0WhA9zsueHHvCZfUNq1sQvfK3DIi9hsRii+N1gTkLa+mkDHz9Ep5uIUtf7LJ/deKnyN4FIvaSRc6vwXtd/0/BLIes7r09btb7L2CDDY0a+G/OXMyBDa7qb0X2ML6fEObg52cDfOVX7aOEhB+q5UUtphQlXMOdyGcoa0sjhsU=,iv:v5xRJzKAM6qDPio8aSltceTJP6Bq79yAC5OvQKV7bHk=,tag:UsaHbGRmbD2Bj7a9Rm3HUw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
