apiVersion: apps/v1
kind: Deployment
metadata:
  name: thetillhoff
  namespace: thetillhoff
spec:
  selector:
    matchLabels:
      app: thetillhoff
  replicas: 2
  template:
    metadata:
      labels:
        app: thetillhoff
    spec:
      containers:
      - name: thetillhoff
        image: ghcr.io/thetillhoff/thetillhoff.de:v0.1.2
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            port: 8080
          initialDelaySeconds: 5
        volumeMounts:
        - name: caddyfile
          subPath: Caddyfile
          mountPath: /etc/caddy/Caddyfile
      volumes:
      - name: caddyfile
        configMap:
          name: caddyfile
