apiVersion: v1
kind: Secret
metadata:
  name: fcp-postgres
  namespace: federated-cloud-platform
stringData:
  user: fcp
  password: CHANGEME
  dsn: postgresql://fcp:CHANGEME@postgres.federated-cloud-platform.svc.cluster.local:5432/fcp?search_path=public&sslmode=disable
