apiVersion: v1
kind: Secret
metadata:
    name: fcp-aws-spot
stringData:
    accessKey: ENC[AES256_GCM,data:wK3DStNwYBjUftRp0jeC9NeD1ec=,iv:TJZTsyLLg8ayztmqyT9/D9jWRSJezDdJTYtKHeqmMLQ=,tag:C/HMCmQPWC/uSphP+2uhBA==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:3pgfYtxrKc/Cu9hl8+rGlvSEUZoQ3uNtit4dzCLaZi531yahZertdQ==,iv:YmAQ8sTQtj0T8Xj7DxG2+VT3SlIUHFc+c9K0AVf1nSw=,tag:c5emeI5tTfFNGutWpCK6AA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSTBZWVRLUStpOU1ZbVBl
            bFBnUzV2RjcrRE1GWm42K3J2M0Y0anB4OVIwCjkydUI1RmRwVUVTdEpUVS9GUjZu
            ZTN6RDYxQ0Fub25vRml1bUtNc01zazgKLS0tIHlhSU83VUYzc21Ydi80SzZlVU1w
            YTdYdUp2dWdWYUM2U0hpRHFGcW5xWE0KuYZIHLcAs/tn4VxQT6CG2DiXU0uAo1BI
            1OhtRuI1PMM1R2gswz73VYl2pXOg0gWkAxEcXAR5bIp+C4KGlfZGKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1068jmwnqrpg6g2m9aswfwz37fjg7vpwtz5vnxlkcwvf3ed8hjaxsycmf85
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ampob3ZNd3JkTlNZanhR
            THpPT0FtRDdNWkhDSVJBM25HeHZudDZib1FJCkNlai9ab0s1Y1k2RjRFWm15SXp5
            eWRia2tWVS9sOVlVQ1FZMDU3VnNEV2sKLS0tIGoyK3ZLVVNZb0ZOWmMwS1ZFcFZa
            NnFsQk1MaFd5bDBEMjJoaVVodzd5VGMKRm5ZvoVw6oKoe72SoSJElNt920Hg9VCb
            BbtmiKhgqR+zP1jv1wDFIm6yOr+E0fe7KigqhMl7+Uv5C2rToysnXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jmznk7lwandq9d7mm6fq69uwpa7hf79p6h6qztz0e20wj2yw2a8qylelvw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T10:07:05Z"
    mac: ENC[AES256_GCM,data:ye5H0SwHBhK2FYedLjcPAPQ0FDpdSQCSCCTi1Vi7le4DWbLRlo3hOkr4CwTYkaQALP3E7i9hlVhFK+cqIRFtBglXJl8jVkVdtHh1Sk5kHM+KoMGn93qU8ouETUN7nKUHz/EhImUj/eAGzLEJQ33rStfmUje9QgqzDx0w1pvcqv0=,iv:GGN+AzwI/mxF4eyYO2fVrCbAG5Xs8yhTWzrF7KHU2EI=,tag:iwiut1F6/JHuKhWZ9up2yQ==,type:str]
    version: 3.13.3
