apiVersion: v1
kind: Secret
metadata:
  name: fcp-scrapers
  namespace: federated-cloud-platform
stringData:
  hetznerKey: CHANGEME   # Team API key for Hetzner scraper
  awsKey: CHANGEME       # Team API key for AWS scraper
  gcpKey: CHANGEME       # Team API key for GCP scraper
  gcpBillingApiKey: ""   # GCP Cloud Billing API key (optional)
  azureKey: CHANGEME     # Team API key for Azure scraper
