apiVersion: v1
kind: Secret
metadata:
    name: fcp-postgres
stringData:
    user: ENC[AES256_GCM,data:FZRh,iv:DTaGa5qgbcQ8nuDpIjmW7aR0ELtjht92jFiLjMFB2ck=,tag:YwnlZyqRGZZ8HPgBU7ga2w==,type:str]
    password: ENC[AES256_GCM,data:Z7x14P/CBH8/K9Pvhp0fke2JxT7BBj5mmf7hxnDfJcKsKufjsrGOSQk8aM6bqqcG,iv:Qbz0aIJp4nNc/o98tuoAguUvNU+RpV/ZrXfrZe74oYE=,tag:yiN9OLvIb7PjNbsoYNAQWw==,type:str]
    dsn: ENC[AES256_GCM,data:ydSg8xzt89fOuUnS8m8q3/9zW9iW4tRIJhBuSbAg12kUg+U5TQzJvuUgPypkNr9Gie5x+S1BrMDNNkYKr0MqU2izZfX4QoH/iU5e3bkkKuv0f1ltqW8PGctAfB4h+vVSevDmrIIHQGDgTnEKAPxRpRoIF8mFr/i7uNdnUSZcGK1isotxjbPIx3FKqrADb27IfLD5RDp1oam2/2e6pBTEBD0=,iv:vFwz3EGpp8YCCEET1pOHT9C7OKFwA2M90tbBd5OVpu4=,tag:wffUsrJgiV0Zyc1pXS+kig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcDRybFpmdlN1R2NTMHhQ
            N1h4bkd6RDdKNmowMy9MdkpENE4xb3V5YUZjClp0MmltWTUvQUJDS2pPWkYxRDBi
            VjRaUTRjY2ZiZjluR3M5eTg4ZTdIMFUKLS0tIEJEeTVSQXloVE1ZOFJPZzhRNUZR
            L3VDcVFKVnFSTWV1VW56YklRNGZMSjgKe2ryyK+Mc/vLlIr6n00MSu0FyIqe2jZJ
            JeF6xm639r+4eelcwnfhGsylGUs+6rl0nxeAkXNWG9SNPrL2EVQtxw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1068jmwnqrpg6g2m9aswfwz37fjg7vpwtz5vnxlkcwvf3ed8hjaxsycmf85
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSnNteFdsMTA5NDVkbHZF
            Zmdua0YrNU5KY2kzSGcvREUxU1hIRXAzNEI4CnRKL0lDNTNaY0U2N3RSR3FsdDh6
            NCt4VlVobVF6VDlYdjYvOGxxNFg3WkEKLS0tIDdXMm9OYzE2YTFvVVhIT1FMWTVF
            UldZN1VlNW93ekxCMWxHeXJITnNVRDAKDCZJxexJsxH2cvmTFi9oUs+CPfVeTaPa
            eJKTF4NqwDEZcMIOSyrzFc4Yd8HnYRF55Pf7RVcfMJ9wsB5AFjnV+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jmznk7lwandq9d7mm6fq69uwpa7hf79p6h6qztz0e20wj2yw2a8qylelvw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T09:50:45Z"
    mac: ENC[AES256_GCM,data:ScXuQHpsXvvEHDamF2PdLNgy0gcwLdsW+4gg8b5buXw7/eMTOA6qzjltb9U0jm8Mt+JXSbyhzoZa06KwZKTN22bTtSy0Csxt5f0z/soXnu0nTN/a1/k7ruDyID+KMe35Qc1EFNVYvJrmQEV4brQ2odhXsh1ZpfhRN8He30JZOwU=,iv:y+NdapsPcEVAp+54YI4MiUIyZuhiYCeO45+Hb6vKPDk=,tag:4kXoQQ8kcxoupeLKvaP7hg==,type:str]
    version: 3.13.3
