apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:DAswZ875Lj189OwQEdbc72wGh7OeXElZ35V+gYMjqPDj0NYbvpU7dVOn+vUHgHw6VFyne8BNumobuwuoh6WSV5dm5lbi3sakCpvgspE9VGCpaGCrQLWBOt9+VF47lmi+958KQO7q2mJ2uHc3ml+DQO7Fr/qBQnelXPlEJQE0loVRJYKaKrxiyusFPM3Ah8YifYjAKd+3glyp84eWp5dGynpFiX5leBq04+jUyWaGedb6Z4FQpRS50lwhAk7LGWwSfsc6SncNn/01lzcHb+sYVn5KpEKs1btMeMIMKkDfPNxTu0uoZa+ikIaHmWi9EWzqSWhwDSzbmVM=,iv:clKOR/YMQoFmHYqlYXMHsJHFdxn2OBzj1KAvfbzlvFg=,tag:kgfCeZ27+Yp/HzBPtgmIew==,type:str]
kind: Secret
metadata:
    name: ghcr-creds
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dzIxUnhjSzdFS0lPZE5y
            amVFZVluUzhiU1Q5U09FSzhrTGlTVjNsN0JZCk43RkZXV2JGYm1iYk53SVk1dkxv
            N0NJdXdUZnpyTjBHN1VScHFQejBmcG8KLS0tIDhHUzBETGY0dkRqbHJVTjJ2WW1T
            ZldXcW5mdlVtV2NFaElxSWdqL3Y2MkUKb2LyFlm/1mlIJ8CeiKnByGxGX8uNfB3B
            dNpleGQr+K9QWiojmMWtTABQHhs3wGr9FRMribSmDVgEhIcSSe5BDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1068jmwnqrpg6g2m9aswfwz37fjg7vpwtz5vnxlkcwvf3ed8hjaxsycmf85
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSml4ZXIyZXNYdEUrZ3Bn
            c2lxRStSQkxCL21iUmQyS1VPRElLcFZCQUIwCno2UWRkcXJaS3ZENndLVlhPanJE
            TUhCWk1xTDZRWGdUVWRPWVVkTUVQT2sKLS0tIDF6NlQvR0hLR09YN1MxeDNQVkhN
            UUJ6c3FWNzZrUndiQkZkR0JvMjB3dEkKdyvRu3VlZd1HTlZRh7U0wl2r6VqU0xNh
            /2nbsTw62SbiIzhWQ37AUg90wfPa/oxhsg15LDY2o+K9URnc04CzBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jmznk7lwandq9d7mm6fq69uwpa7hf79p6h6qztz0e20wj2yw2a8qylelvw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T09:47:52Z"
    mac: ENC[AES256_GCM,data:P6lJBtYL5IuQRlf42NMnzYNyvdbK6Q/qQ+L/Bdxt8XXbB36N9mxiABuFjbhxQP49Ea2KZfG9w+jSqF/Gaw4VfLifzHJrdrDKXF0K/9rbsPIVoBtA0PNDMCvC0BZF7t1scjFaZ7dQReaUYaO9PNw2vWieVaCjX3iF+xOmtRfm8bo=,iv:yAUCCr4qz+MyJFDN6/wYltQj8Ehyb9UkwwPt4MCrpYo=,tag:2XkJ8hIo0bVY+jGu9g8Mow==,type:str]
    version: 3.13.3
