apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: fcp-scrape-azure
  namespace: federated-cloud-platform
spec:
  image: ghcr.io/thetillhoff/federated-cloud-platform/scrape-azure
  interval: 5m0s
  secretRef:
    name: ghcr-creds
