apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-web
  namespace: federated-cloud-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: public-web
  template:
    metadata:
      labels:
        app: public-web
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: public-web
          image: ghcr.io/thetillhoff/federated-cloud-platform/public-web:43 # {"$imagepolicy": "federated-cloud-platform:fcp-public-web"}
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: public-web
  namespace: federated-cloud-platform
spec:
  selector:
    app: public-web
  ports:
    - port: 8080
      targetPort: 8080
