apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: pihole
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: http
  - port: 53
    targetPort: 53
    protocol: tcp
  - port: 53
    targetPort: 53
    protocol: udp
  selector:
    app: pihole
