apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: acme-resolver-gateway
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
