apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
- namespace.yaml
- metrics-server
# - helmRepository-grafana-labs.yaml
# - prometheus
# - loki
# - alloy
