apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: 4.8.3
  interval: 10m

  values:
    controller:
      config:
        ssl-protocols: TLSv1.2 TLSv1.3 # set by default anyway

        enable-modsecurity: "true"
        enable-owasp-modsecurity-crs: "true"

        # hsts: true
        # hsts-max-age: ...

        keep-alive: "10" # seconds

        ssl-ciphers: EECDH+AESGCM:EDH+AESGCM
        # ssl_prefer_server_ciphers is enabled by default
        ssl-dh-param: "ingress-nginx/dh-param" # name of the secret

        use-gzip: "true"
        enable-brotli: "true"

        # allow-snippet-annotations: "true" # enabled by default -> already defined in configmap
