apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kubernetes/apps/pegasus
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
