apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- # Gateway API CRDs
  https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/standard-install.yaml
# - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.0/deploy/static/provider/baremetal/deploy.yaml

# configMapGenerator:
# - name: ingress-nginx-config
#   files:
#   - ingress-nginx.config
