- ufw: # allow connections from private ips
    rule: allow
    port: '443'
    proto: tcp

- ansible.builtin.find:
    paths: infra/kubernetes/apps/{{ lookup('env', 'CLUSTER_NAME') }}
    recurse: yes
    patterns: '*.gpg'
  register: secret

- set_fact:
    secret_files: []
- set_fact:
    secret_files: "{{ secret_files + [item.path] }}"
  with_items: "{{ secret.files }}"

- shell: echo "{{ item }}"
  with_items: secret_files

- shell: gpg --batch --yes --decrypt --passphrase '{{ lookup('env', 'GPG_PASSWORD') }}' -o '{{ item }}' '{{ item }}'
  with_items: secret_files

- shell: kubectl apply -k ./apps/{{ lookup('env', 'CLUSTER_NAME') }}
  args:
    chdir: infra/kubernetes
