- ufw: # allow connections from private ips
    rule: allow
    port: '443'
    proto: tcp

- shell: ./transcrypt -y -c aes-256-cbc -p "{{ lookup('env', 'TRANSCRYPT_PASSWORD') }}"
  ignore_errors: true # will fail if already configured
  args:
    chdir: infra

- shell: kubectl kustomize --enable-helm ./ | kubectl apply -f -
  args:
    chdir: infra/kubernetes
