- ufw: # allow connections from private ips
    rule: allow
    port: '443'
    proto: tcp

- shell: ./transcrypt -c aes-256-cbc -p "{{ lookup('env', 'TRANSCRYPT_PASSWORD') }}"
  args:
    chdir: infra

- shell: kubectl apply --prune --all -k ./apps/{{ lookup('env', 'CLUSTER_NAME') }}
  args:
    chdir: infra/kubernetes
