- ufw: # allow connections to https
    rule: allow
    port: '443'
    proto: tcp

- shell: ./transcrypt -y -c aes-256-cbc -p "{{ lookup('env', 'TRANSCRYPT_PASSWORD') }}"
  ignore_errors: true # will fail if already configured
  args:
    chdir: infra

# install fluxcd
- shell: curl -s https://fluxcd.io/install.sh | sudo bash
  # environment:
  #   FLUX_VERSION: "2.4.0"
  args:
    creates: /usr/local/bin/flux

- shell: | # Bootstrap flux
    flux bootstrap github \
    --owner=thetillhoff --repository=infra --path=kubernetes/clusters/{{ ansible_hostname }} --components-extra=image-reflector-controller,image-automation-controller
  environment:
    GITHUB_TOKEN: "{{ lookup('env', 'GITHUB_TOKEN') }}"

- shell: | # Check if sops-age secret exists
    kubectl get secret -n flux-system sops-age
  register: get_sops_secret
  ignore_errors: true

# Create sops-age secret after flux is bootstrapped, so the namespace exists beforehand, but only if it doesn't already exist
- shell: kubectl create secret generic sops-age -n flux-system --from-literal=identity.agekey='{{ lookup('env', 'AGE_KEY') }}'
  when: get_sops_secret is failed
