- ufw: # allow connections from private ips
    rule: allow
    port: '443'
    proto: tcp

- shell: find . -name '*.gpg' -exec gpg --batch --yes --decrypt --passphrase '{{ lookup('env', 'GPG_PASSWORD') }}' -o '\{\}' '\{\}' \\\;
  args:
    chdir: infra/kubernetes/apps/{{ lookup('env', 'CLUSTER_NAME') }}

- shell: kubectl apply -k ./apps/{{ lookup('env', 'CLUSTER_NAME') }}
  args:
    chdir: infra/kubernetes
