- ufw: # allow connections from private ips
    rule: allow
    port: '443'
    proto: tcp

- ansible.builtin.find:
    paths: infra/kubernetes/apps/{{ lookup('env', 'CLUSTER_NAME') }}
    recurse: yes
    patterns: '*.gpg'
  register: secrets

- shell: echo {{ item.path }}
  with_items: "{{ secrets }}"

- shell: gpg --batch --yes --decrypt --passphrase '{{ lookup('env', 'GPG_PASSWORD') }}' -o '{{ item.path }}' '{{ item.path }}'
  with_items: "{{ secrets }}"

- shell: kubectl apply -k ./apps/{{ lookup('env', 'CLUSTER_NAME') }}
  args:
    chdir: infra/kubernetes
