- ufw: # allow connections to https
    rule: allow
    port: '443'
    proto: tcp

- shell: ./transcrypt -y -c aes-256-cbc -p "{{ lookup('env', 'TRANSCRYPT_PASSWORD') }}"
  ignore_errors: true # will fail if already configured
  args:
    chdir: infra

# install fluxcd
- shell: curl -s https://fluxcd.io/install.sh | sudo bash
  args:
    creates: /usr/local/bin/flux

- copy:
    src: ../deploy.key
    dest: ./deploy.key
    chmod: '0600'

- shell: | # Bootstrap flux
    flux bootstrap git \
    --url=ssh://git@github.com/thetillhoff/infra
    --branch=main \
    --path=kubernetes/clusters/{{ ansible_hostname }} \
    --private-key-file=./deploy.key

# - shell: kubectl apply -k ./apps/{{ ansible_hostname }}-crds
#   args:
#     chdir: infra/kubernetes

# #- shell: kubectl apply --prune --all --prune-whitelist=apiextensions.k8s.io/v1/customresourcedefinition -k ./apps/{{ ansible_hostname }}
# - shell: kubectl apply -k ./apps/{{ ansible_hostname }}
#   args:
#     chdir: infra/kubernetes
