- apt:
    pkg:
      - dpkg-dev
      - linux-headers-generic
      - zfs-dkms
      - zfsutils-linux

- community.general.modprobe:
    name: zfs
    state: present

- stat:
    path: /mnt/hot
  register: storage_dir
- when: not storage_dir.stat.exists
  block:
    - command: "sgdisk --zap-all /dev/disk/by-id/ata-{{ item }}"
      loop:
      - Samsung_SSD_850_EVO_250GB_S2R6NX0JB23647W
      - Samsung_SSD_860_EVO_250GB_S3YJNX0KB49233X
    - command: partprobe
      # inform kernel about partition changes
    - command: |
        zpool create -m /mnt/hot -f hot mirror -o feature@lz4_compress=enabled
        /dev/disk/by-id/ata-Samsung_SSD_850_EVO_250GB_S2R6NX0JB23647W
        /dev/disk/by-id/ata-Samsung_SSD_860_EVO_250GB_S3YJNX0KB49233X
      # Since compression is enabled by default for zfs, and the default is either lzjb or lz4 (if this feature is enabled) the latter makes more sense, since it is way faster on both compressable and non-compressable data.

- stat:
    path: /mnt/cold
  register: storage_dir
- when: not storage_dir.stat.exists
  block:
    - command: "sgdisk --zap-all /dev/disk/by-id/ata-{{ item }}"
      loop:
      - WDC_WD30EZRX-00D8PB0_WD-WCC4N0CNYEZD
      - WDC_WD30EZRX-00D8PB0_WD-WCC4N1XYTYZY
      - WDC_WD30EZRX-00D8PB0_WD-WCC4N2TXL9J4
    - command: |
        zpool create -m /mnt/cold -f cold raidz -o feature@lz4_compress=enabled
        /dev/disk/by-id/ata-WDC_WD30EZRX-00D8PB0_WD-WCC4N0CNYEZD
        /dev/disk/by-id/ata-WDC_WD30EZRX-00D8PB0_WD-WCC4N1XYTYZY
        /dev/disk/by-id/ata-WDC_WD30EZRX-00D8PB0_WD-WCC4N2TXL9J4
      # Since compression is enabled by default for zfs, and the default is either lzjb or lz4 (if this feature is enabled) the latter makes more sense, since it is way faster on both compressable and non-compressable data.
      #-o casesensitivity=mixed -o nbmand=on


# install samba
- apt:
    pkg:
      - samba

# allow SMB port/s
- ufw: # allow connections to port
    rule: allow
    port: 137
    proto: udp
- ufw: # allow connections to port
    rule: allow
    port: 138
    proto: udp
- ufw: # allow connections to port
    rule: allow
    port: 139
    proto: tcp
- ufw: # allow connections to port
    rule: allow
    port: 445
    proto: tcp


# create public shared folder and set permissions on it
- ansible.builtin.file:
    path: "/mnt/cold/public"
    state: directory
    mode: '0777'
    recurse: yes

# create users for shares
- ansible.builtin.user:
    name: '{{ item.name }}'
    password: '{{ item.passhash }}' # password can be generated with `mkpasswd --method=sha-512`
    home: '/mnt/cold/{{ item.name }}'
  loop:
  - name: 'backup'
    passhash: '$6$BTghggjHZA$SyMHrFe7dLamQPsilwJE4PLlcAzk09Bq6D9cBB6SMAruDA.usJ.ka3LJOk8VGukR4XGSkyXr2ZhlBgr59fuxu0'
  - name: 'backupp'
    passhash: '$6$somesalt$ZlH6KQUe0X5MfWe92Sb/SiHZVGUg25YKe/EeH9RpavT8GHPryq188CnOmddX1YBirKLfyoUVrlgIJS.RmPUF0/'
  register: smbusers

# # create shared folder and set permissions on it
# - ansible.builtin.file:
#     path: "/mnt/cold/{{ item.name }}"
#     state: directory
#     mode: '0755'
#     recurse: yes
#     owner: "{{ item.name }}"
#     group: "{{ item.name }}"
#   loop: "{{ smbusers }}"

- ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
  vars:
    publicshares:
    - public
    usershares:
    - backup
    - backupp
  register: smbconf

- ansible.builtin.service:
    name: smbd
    state: restarted
  when: smbconf.changed or smbusers.changed
