apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: link-shortener
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- httpRoute-http.yaml
- httpRoute-https.yaml

- imageRepository.yaml
- imagePolicy.yaml
- imageUpdateAutomation.yaml

configMapGenerator:
- name: caddyfile
  namespace: link-shortener
  files:
    - Caddyfile
