apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: postgres
spec:
  imageRepositoryRef:
    name: postgres
  filterTags:
    pattern: '^17.(?P<version>.*)'
    extract: '$version'
  policy:
    numerical:
      order: asc
