apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: umami
resources:
- namespace.yaml
- statefulset-postgres.yaml
- service-db.yaml
- statefulset-umami.yaml
- service-umami.yaml
- db.secret.yaml
- umami.secret.yaml

# Disabled until https://github.com/getsops/sops/issues/1886 is solved
# secretGenerator:
#   - name: mysql
#     envs:
#       - mysql.secret.env
#   - name: umami
#     envs:
#       - umami.secret.env
