apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: umami
resources:
- namespace.yaml
- statefulset-mysql.yaml
- service-mysql.yaml
- statefulset-umami.yaml
- service-umami.yaml

secretGenerator:
  - name: mysql
    files:
      - mysql.secret.yaml
  - name: umami
    files:
      - umami.secret.yaml
