apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: mysql
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:TzfAPiaC9RSOP15cs9LGeJEsE/Rw7WWE+t5ki0G5u0CbhQVX4nkDgQ==,iv:Zqf7e3/wP6N3pi92D8Z+VixPVdh12QbfKC1Rq4WwoFM=,tag:OH/G/inZTUamrAxZ3ZR3wQ==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:BVuCku8=,iv:tQWPUudHmi0xf6Whq+Am+Kjty3YE5Kgyu4PeZj64cvM=,tag:inEfmViu1pQZXRtdydRx8Q==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:7N7RVec7hcXz5yjS4KtuekJ6ADFFTf7vsc5stal01MipOZMv+zl9,iv:0x9RxarOcQxXNRwYHQrTNrTN9hBRuRLH7fymnnRAKZw=,tag:iylFMxJkAutT2RSN1hSxZA==,type:str]
    MYSQL_DATABASE: ENC[AES256_GCM,data:PwL7uTs=,iv:BrlyYjvScUnW3DxbK3S8TSbbtGNsjdjT2stF3xHdUn0=,tag:qLL6oYqPr9XGyrr6z3j6YQ==,type:str]
sops:
    age:
        - recipient: age1068jmwnqrpg6g2m9aswfwz37fjg7vpwtz5vnxlkcwvf3ed8hjaxsycmf85
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeWl6MU85K21YTWpEaExE
            Z3REWVBBVzUxRG1xMUc2a3BGL0Rkdkxmc3hVCnU5anl4TUhrMy9nK0pxSkwvQlRM
            VEgrUWo1bHBHOWh6dThaSGNrdjZlaEUKLS0tIDNveEFCVHV3d3NKWnpPZ29jcGtj
            K013RlBIM0xxWjArem1yUG5jNGpWYncKKDE8tVjmEnmh0ntgILVZ1J0+rqfNv+wx
            NWh3XE+QrWNSMyJ/XC8SdeZp2nsAeHIPpCnkpW5nt4ta5viZezRubQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jmznk7lwandq9d7mm6fq69uwpa7hf79p6h6qztz0e20wj2yw2a8qylelvw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYWdUbEMrSW9QelFiaGtL
            cWtxZC9UeEsxc1Qwa1l3WlhuZ2IwZ0VkRWxjCnp0aTdwQjlOUVJXcCtPSXBGMGdr
            UzMyYk1GSS9WN0lTYkVEOHUvdm5hTXcKLS0tIFJWK1JjM3RJV3owU285WndZa0cy
            Uzl0aVZFdXYvWGdnUWtzY3puNkFGSW8KxbtUnaKlojShIl50qUenE0lWJZ0Cmvj7
            2S6Rvyp0DFPyz5mH/A2tvbqjPGyoOgaEOnFJ9+pymEaca/EddolMgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-05T21:29:39Z"
    mac: ENC[AES256_GCM,data:IGsMYRqyG0dKPBFheSw6EhwZ4iS82oT5vsiw3QKfON43BjyZl/OJgelHbwWXrxWePIHw1aXLlQe8Zotrz/46/qx8BFI0V6kiNDpsFkPRwRju6NuM7t0NIlQhWSZzk8YJTuymsEyiTe1BZdgI1H0LINDNLEfaSeTE2hZMeDlTsjM=,iv:86L5jfDtJ7jU1o9raOPb2jhmxcplHw4zNelDMpXZWNE=,tag:MF1aFyiRsR3hEP6yfIyb3w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
