apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  serviceName: db
  selector:
    matchLabels:
      app: db
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:17.5 # {"$imagepolicy": "umami:postgres"}
        ports:
        - containerPort: 5432
          livenessProbe:
            initialDelaySeconds: 30
            exec:
              command: ["pg_isready"]

        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db
              key: POSTGRES_USER

        # Fixing the following error:
        # initdb: error: directory "/var/lib/postgresql/data" exists but is not empty
        # initdb: detail: It contains a lost+found directory, perhaps due to it being a mount point.
        # initdb: hint: Using a mount point directly as the data directory is not recommended.
        # Create a subdirectory under the mount point.
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata

        volumeMounts:
        - name: db-data
          mountPath: "/var/lib/postgresql/data"

  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 10Gi
