apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: umami
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:Fkz+GW2zvNaPbjcFjYDEjtufLHLu1q0UgFt+iaCC5G+HAOnFK8S+eoUOKBTp+S7aP8rRlWRZyLGqdivAEJW7IinxIVZbWw==,iv:sLX6hlZzTs5MtSo/oXBsmSFnW55haYQwFHH141CtbI4=,tag:vrXy2d+6csVuMIuNJAdF4g==,type:str]
sops:
    age:
        - recipient: age1068jmwnqrpg6g2m9aswfwz37fjg7vpwtz5vnxlkcwvf3ed8hjaxsycmf85
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcUVoZ0U0VVhkc2ZSTFpa
            a0VuR29Na01MVWJUbDA3KytnOVJyaFJZaDEwCk1QUFF4bWdXdDhFQUtndFY0VHVs
            dVFIdWZMaFAxdEFwbTF0Q0hsYzRUTDQKLS0tIEhwNktmaTR1elkwNkdZZGhOREdW
            cWJHUFFKYWQxb0FhWkcyajlNbkhVZVkKDcr63UbYJywLymlukG7qrt/Wzd1Y28Pe
            DCEeqKMkdwqDBOZroxMhKu1yFE9WxxuioX2DLBExAo0TNTI5Mnn0sQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jmznk7lwandq9d7mm6fq69uwpa7hf79p6h6qztz0e20wj2yw2a8qylelvw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUEhSQy9YRkNFZnpHTUU5
            YlNrRW5JYWJ1d25JeHZJNGFEYVhTZ1F5Nm5nClVmbVliQ0dRWHByYmZXaE9ZMk5L
            U0JJaUpLY2FVMW1tVDlPb1FJdFd5VFUKLS0tIG1UUEcxd0NINDlwYkJSV0pyTzll
            QVYycVkvQXVuelRpUnh1M0xQY0l0TTAKm5LP5W5qsBECJN6WHVYNpqdibiwWjJLf
            sb0urtyx0iikw2QuTbXOGBpipCfgx4y+eFz2OlqCSKs8tF7017mMEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-05T21:30:02Z"
    mac: ENC[AES256_GCM,data:aeJsMnkIyCYwgCNLZOwLSPD/KvolzMB3LT1berV8ENSSbSMEiwBKPEoj23stv/IKHWiHmUzLMbf81sq2jAAjxWqtadYxQlEeC2iSW4IoHbZtu+f/hxKmBmqaZrkxQCnM4BBJp/fBfz5U+bH4px4LX0zjKmZ0cts5r7Vz89jgpp8=,iv:KgYpk8l6x5HDj7R4++qzgH7h4UJC+a2oUoR/rR8U6ag=,tag:YFzvy146ONpTccLozMs5fg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
