apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  chart:
    spec:
      chart: metrics-server
      version: 3.12.2
      sourceRef:
        kind: HelmRepository
        name: metrics-server
  interval: 10m

  valuesFrom:
    - kind: ConfigMap # This value is case sensitive
      name: metrics-server-helm-values # automatically overridden by kustomize
      # valuesKey: values.yaml # `values.yaml` is the default key
