# kubeadm init and kubeconfig creation

- stat:
    path: /etc/kubernetes/admin.conf
  register: kube_config

- when: not kube_config.stat.exists
  shell: "kubeadm init --config /tmp/kubeadm-clusterconfiguration.yaml --control-plane-endpoint {{ lookup('env', 'CONTROL_PLANE_ENDPOINT') }} --ignore-preflight-errors=NumCPU"
- when: not kube_config.stat.exists
  shell: "kubectl taint nodes --all node-role.kubernetes.io/master-" # enable workloads on master nodes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
