apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- Namespace.yaml
- StatefulSet.yaml

configMapGenerator:
- name: smb-config
  namespace: smb-shares
  files:
    - smb-config.yaml
