apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscaile
spec:
  selector:
    matchLabels:
      app: tailscaile
  replicas: 1
  template:
    metadata:
      labels:
        app: tailscaile
    spec:
      containers:
      - name: tailscaile
        image: ghcr.io/tailscale/tailscale:v1.84.3 # {"$imagepolicy": "tailscale:tailscale"}
        livenessProbe:
          httpGet:
            port: 9002
            path: /healthz
          initialDelaySeconds: 30
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_MODULE
        env:
        - name: TS_ENABLE_HEALTH_CHECK
          value: "true"
        - name: TS_KUBE_SECRET
          value: "tailscale"
