kind: Secret
apiVersion: v1
metadata:
    name: tailscale
type: Opaque
stringData:
    authkey: ENC[AES256_GCM,data:frMtkfbZgb+SfKB+N2HTVjOqYWnIPb8m9XCYxtXRlrh2T82FyyZXO5REof2mFDBXQApmJitI1W1b,iv:XtMTrDQlI+uFIp7Ai8afbqd+cQQzY6QA75EVMPpmbM8=,tag:mKMPLgsElUNDPT7DPJDB1g==,type:str]
sops:
    age:
        - recipient: age1068jmwnqrpg6g2m9aswfwz37fjg7vpwtz5vnxlkcwvf3ed8hjaxsycmf85
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVWJFT2xJNXZMbzBQZGRm
            bDB4eTJFbFhEbjBMZHdoUkV4dXA5c0xyejNJClZPSUQ3YWVXTkNYMXdpMXZrTTJQ
            YXJxZE9JOHJrNk5VYTdJS3pSV3Z5OVkKLS0tIHpZbTczbjdFNThXK2plWUo4cnZS
            djhXUC8ySGg0NEpGRlZiNlRCWVljZGMKyOWSXhoNzPjRZd8Iw/xYAqjppB8JZPzA
            IC/wan4MuUPHbF5l6H7T4beee1k2fEw+UYHVPcdJUpmvfK7gHfCqRA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jmznk7lwandq9d7mm6fq69uwpa7hf79p6h6qztz0e20wj2yw2a8qylelvw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSU9vZGZlOVJqYU5vb3Vp
            cTJiRzFiWDFobDlSZDRucG5qdGRrdjJqS2s4ClNBTWVOVk0raGxCQUF3VmVES1lC
            dWR3WksrU3pTb2liL1Rrb0k0Ly9XTGcKLS0tIDlvbXVPcEpGY3NidUdSdGVhM0lX
            dThscncrM2ZlbHdPY0JWQzMxSUFWWW8KQwLZPJTs4Th0lXZgzXgwZihHwknLsnPq
            oF4HP/IjqLEpfFe93erTmHAuggx9c5dESWWK6I3O6uevFIb9fX849A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-06T14:57:59Z"
    mac: ENC[AES256_GCM,data:1Be5Z+J3bQk4hjs7N0neDzbMGwSwZICoRW/g0zKu2J1y6Y7t2TangOMGiXNNVYklqzsHqGfwrSNiucE/tG/f8wFH4+mEOzEbpAnyXWUC7O9bv2ut1QSFbL8bOUR8OVfeJZXhbv00wuzVWL0cydzISPZUB8iq9B463jOeXXFqXKo=,iv:W2vY4cKv/CoTEGeDQqDGPdY8vuZgi33v7aMYL2HMPfA=,tag:o7GuvUpGVuYfLwh6yKDMiQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
