apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:2mWGFtVL3aMsSRwbjJ8rWdHiuqO0EHGq+rj5quJi7zYj903BjtlY8Q==,iv:wtilTWzuJV+qSczR+44TJ9uz2KFxbN4PExongn0GNfI=,tag:mMA6meASDo/EvyksGskvLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVG9HY0x3b0FYaElLY08y
            RWtqK1NDUXRwakJHMzl0WjdSazJJU2ZZTGhZCkJnU2hFOG9qeS9hN285UHJETVNw
            N1R2UUZ4UCsyUElzVnV1RUVXWU15UW8KLS0tIFN1VXVocnd1NmNLVnlEeG0reGo5
            OVdHdlFEYlk0S2xneXovdGlpeDVkS3MK4BSijDeZ6H9OgcqEoqX36dyC9mzABHTV
            eGfEwXJDD9EpgvB77E6JacQJL+6rtMLlotL8T5Cxa87Pn06KjxC2KQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1068jmwnqrpg6g2m9aswfwz37fjg7vpwtz5vnxlkcwvf3ed8hjaxsycmf85
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5YS9BaU1oc3YwWlFGV0Jv
            VTUvb1kyR2hwMHRKMG56SEo1WjE5TkJoenk0CkFZREUxbDd4QXVCR05GRnphYVYy
            aDQwb3ZTNGc5QlBndExCRTBzWHFzclUKLS0tIDUzaE5oS1ExOHk1eUhLS2VBZnZT
            MDZlcW9nTW54TDliT0xuVUtRV2F4MDgK9sISP0OxRkyITV1yHJUzKYYUIbO9DPdf
            VD19UI9Fk9ku8uB69VlqcfHtywGpysPYXkCUHNl45dyCboL1funyHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jmznk7lwandq9d7mm6fq69uwpa7hf79p6h6qztz0e20wj2yw2a8qylelvw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-06T23:28:22Z"
    mac: ENC[AES256_GCM,data:Jwoam9cPn8alE8aOMsX+1lnypZx4i+E7KyAU0+f7QNUBxlGZm1YhQ6VBTgViq+qEM5+djtxLo0QMCJ+7BH9xcK2aD0upPLwUsS7CMFuyy8diFERWGR1spFmVH7O6lGu8Gqm/GTcg+TlqdcT95RFGxHPN/SCZfqzDU9ljf/oWY9w=,iv:br1SGzTjwU8Un3zpVowFwkwToRwAMoEVq4BN6yMKh7Q=,tag:adkdG8OqphD27bliBzekpQ==,type:str]
    version: 3.13.2
