- stat:
    path: /etc/rancher/k3s/config.yaml
  register: k3s_config

- when: not k3s_config.stat.exists
  ansible.builtin.file:
    path: /etc/rancher/k3s/
    state: directory

- when: not k3s_config.stat.exists
  ansible.builtin.copy:
    content: |
      # default storage path: /opt/local-path-provisioner
      #default-local-storage-path: ...
    dest: /etc/rancher/k3s/config.yaml


- stat:
    path: /var/lib/rancher/k3s/server/manifests/cert-manager.yaml
  register: cert_manager_k8s_manifest

- when: not cert_manager_k8s_manifest.stat.exists
  ansible.builtin.file:
    path: /etc/rancher/k3s/
    state: directory

- when: not cert_manager_k8s_manifest.stat.exists
  ansible.builtin.get_url:
    url: https://github.com/cert-manager/cert-manager/releases/download/v1.8.0/cert-manager.yaml
    dest: /var/lib/rancher/k3s/server/manifests/cert-manager.yaml


- ansible.builtin.shell: curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s


- stat:
    path: /root/.kube/config
  register: kube_config

- when: not kube_config.stat.exists
  ansible.builtin.file:
    path: /root/.kube/
    state: directory

- when: not kube_config.stat.exists
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /root/.kube/config
    remote_src: yes
