- stat:
    path: /etc/rancher/k3s/config.yaml
  register: k3s_config

- when: not k3s_config.stat.exists
  ansible.builtin.file:
    path: /etc/rancher/k3s/
    state: directory

- when: not k3s_config.stat.exists
  ansible.builtin.copy:
    content: |
      # bind-address: {{ tailscale_ip.stdout }}
      # flannel-backend: wireguard
      # default storage path: /opt/local-path-provisioner
      #default-local-storage-path: ...
    dest: /etc/rancher/k3s/config.yaml

- ansible.builtin.shell: curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s

- stat:
    path: /root/.kube/config
  register: kube_config

- when: not kube_config.stat.exists
  ansible.builtin.file:
    path: /root/.kube/
    state: directory

- when: not kube_config.stat.exists
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /root/.kube/config
    remote_src: yes
