# k3s prerequisites
- apt:
    pkg:
      - apparmor-utils # Used to prevent the k3s logs to be spammed with apparmor errors

# k3s config
- stat:
    path: /etc/rancher/k3s/config.yaml
  register: k3s_config

- when: not k3s_config.stat.exists
  file:
    path: /etc/rancher/k3s/
    state: directory

- when: not k3s_config.stat.exists
  copy:
    content: |
      disable: traefik
      # default storage path: /opt/local-path-provisioner
      #default-local-storage-path: ...
    dest: /etc/rancher/k3s/config.yaml

# k3s
- shell: curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s

# kube config
- stat:
    path: /root/.kube/config
  register: kube_config

- when: not kube_config.stat.exists
  file:
    path: /root/.kube/
    state: directory

- when: not kube_config.stat.exists
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /root/.kube/config
    remote_src: yes
