apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
spec:
  chart:
    spec:
      chart: promtail
      version: 6.17.0
      sourceRef:
        kind: HelmRepository
        name: grafana-labs
  interval: 10m

  valuesFrom:
    - kind: ConfigMap # This value is case sensitive
      name: promtail-helm-values # automatically overridden by kustomize
      # valuesKey: values.yaml # `values.yaml` is the default key
