- ansible.builtin.apt_repository:
    repo: deb http://deb.debian.org/debian bullseye-backports main contrib
    state: present
  register: apt_zfs_repo

- when: apt_zfs_repo.changed
  apt:
    update_cache: yes

# apt zfs onfig
- stat:
    path: /etc/apt/preferences.d/90_zfs
  register: apt_zfs_preferences

- when: not apt_zfs_preferences.stat.exists
  ansible.builtin.file:
    path: /etc/apt/preferences.d/
    state: directory

- when: not apt_zfs_preferences.stat.exists
  ansible.builtin.copy:
    content: |
      Package: libnvpair1linux libnvpair3linux libuutil1linux libuutil3linux libzfs2linux libzfs4linux libzpool2linux libzpool4linux spl-dkms zfs-dkms zfs-test zfsutils-linux zfsutils-linux-dev zfs-zed
      Pin: release n=bullseye-backports
      Pin-Priority: 990
    dest: /etc/apt/preferences.d/90_zfs

- apt:
    pkg:
      - dpkg-dev
      - linux-headers-generic
      - linux-image-amd64
      - zfs-dkms
      - zfsutils-linux

- community.general.modprobe:
    name: zfs
    state: present

- stat:
    path: /mnt/hot
  register: storage_dir
- when: not storage_dir.stat.exists
  block:
    - command: "sgdisk --zap-all /dev/disk/by-id/ata-{{ item }}"
      loop:
      - Samsung_SSD_850_EVO_250GB_S2R6NX0JB23647W
      - Samsung_SSD_860_EVO_250GB_S3YJNX0KB49233X
    - command: partprobe
      # inform kernel about partition changes
    - command: |
        zpool create -m /mnt/hot -f hot mirror -o feature@lz4_compress=enabled
        /dev/disk/by-id/ata-Samsung_SSD_850_EVO_250GB_S2R6NX0JB23647W
        /dev/disk/by-id/ata-Samsung_SSD_860_EVO_250GB_S3YJNX0KB49233X
      # Since compression is enabled by default for zfs, and the default is either lzjb or lz4 (if this feature is enabled) the latter makes more sense, since it is way faster on both compressable and non-compressable data.

- stat:
    path: /mnt/cold
  register: storage_dir
- when: not storage_dir.stat.exists
  block:
    - command: "sgdisk --zap-all /dev/disk/by-id/ata-{{ item }}"
      loop:
      - WDC_WD30EZRX-00D8PB0_WD-WCC4N0CNYEZD
      - WDC_WD30EZRX-00D8PB0_WD-WCC4N1XYTYZY
      - WDC_WD30EZRX-00D8PB0_WD-WCC4N2TXL9J4
    - command: |
        zpool create -m /mnt/cold -f cold raidz -o feature@lz4_compress=enabled
        /dev/disk/by-id/ata-WDC_WD30EZRX-00D8PB0_WD-WCC4N0CNYEZD
        /dev/disk/by-id/ata-WDC_WD30EZRX-00D8PB0_WD-WCC4N1XYTYZY
        /dev/disk/by-id/ata-WDC_WD30EZRX-00D8PB0_WD-WCC4N2TXL9J4
      # Since compression is enabled by default for zfs, and the default is either lzjb or lz4 (if this feature is enabled) the latter makes more sense, since it is way faster on both compressable and non-compressable data.
