- ansible.builtin.apt_repository:
    repo: deb http://deb.debian.org/debian bullseye-backports main contrib
    state: present
  register: apt_zfs_repo

- when: apt_zfs_repo.changed
  apt:
    update_cache: yes

# apt zfs onfig
- stat:
    path: /etc/apt/preferences.d/90_zfs
  register: apt_zfs_preferences

- when: not apt_zfs_preferences.stat.exists
  ansible.builtin.file:
    path: /etc/apt/preferences.d/
    state: directory

- when: not apt_zfs_preferences.stat.exists
  ansible.builtin.copy:
    content: |
      Package: libnvpair1linux libnvpair3linux libuutil1linux libuutil3linux libzfs2linux libzfs4linux libzpool2linux libzpool4linux spl-dkms zfs-dkms zfs-test zfsutils-linux zfsutils-linux-dev zfs-zed
      Pin: release n=bullseye-backports
      Pin-Priority: 990
    dest: /etc/apt/preferences.d/90_zfs

- apt:
    pkg:
      - dpkg-dev
      - linux-headers-generic
      - linux-image-amd64
      - zfs-dkms
      - zfsutils-linux

- community.general.modprobe:
    name: zfs
    state: present

- block:
    - command: "sgdisk --zap-all {{ item }}"
      with_fileglob: '/dev/disk/by-id/ata-Samsung*'
    - command: zpool create -m /mnt/hot -f hot mirror -o feature@lz4_compress=enabled {{ lookup('ansible.builtin.fileglob', '/dev/disk/by-id/ata-Samsung*') }}
      # Since compression is enabled by default for zfs, and the default is either lzjb or lz4 (if this feature is enabled) the latter makes more sense, since it is way faster on both compressable and non-compressable data.
  args:
    creates: /mnt/hot

- block:
    - command: "sgdisk --zap-all {{ item }}"
      with_fileglob: '/dev/disk/by-id/ata-WDC*'
    - command: zpool create -m /mnt/cold -f cold raidz -o feature@lz4_compress=enabled {{ lookup('ansible.builtin.fileglob', '/dev/disk/by-id/ata-WDC*') }}
      # Since compression is enabled by default for zfs, and the default is either lzjb or lz4 (if this feature is enabled) the latter makes more sense, since it is way faster on both compressable and non-compressable data.
  args:
    creates: /mnt/cold
