- name: Install rook
  shell: |
    helm repo add rook https://charts.rook.io/release
    helm upgrade --install rook-operator rook/rook-ceph -f rook-operator.values.yaml --namespace rook --create-namespace
    kubectl apply -f rook-toolbox.deployment.yaml --namespace rook
    kubectl apply -k ./rook --namespace rookkub
  args:
    chdir: infra/kubernetes
