apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
spec:
  chart:
    spec:
      chart: alloy
      version: 1.1.1
      sourceRef:
        kind: HelmRepository
        name: grafana-labs
  interval: 10m

  valuesFrom:
    - kind: ConfigMap # This value is case sensitive
      name: alloy-helm-values # automatically overridden by kustomize
      # valuesKey: values.yaml # `values.yaml` is the default key
