apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wedding-website
resources:
- namespace.yaml
- ghcr-pull.secret.yaml
- wedding-password.secret.yaml

- pvc.yaml
- deployment.yaml
- service.yaml
- httpRoute-http.yaml
- httpRoute-https.yaml

- imageRepository.yaml
- imagePolicy.yaml
- imageUpdateAutomation.yaml
