apiVersion: v1
kind: Secret
metadata:
    name: wedding-smtp
stringData:
    #ENC[AES256_GCM,data:/7Xqujy4oi6Nl3JsuwhCUWUs4noObb+OViLPW25cMmKmpOMgMDcJH73/GvG6zME1EULg6/31d+8e9i405bZggWh6P+lmh55Zl6iLhBaHO3cQECiJ,iv:FSajpBeJXYoslSoP5IAHaQOEWgpJ4Agn2l+cvMZdGqQ=,tag:mPwbk0/rohiR31cgC7kzhw==,type:comment]
    user: ENC[AES256_GCM,data:+XUvwAfMU2WnMa1x76sfWRvmbAwx,iv:lBwLG/FUkMWHETxhqF7XcKAfs4q5PFTP1rIu1rj8QYc=,tag:tbQ63PxEzadEesEg7t4miw==,type:str]
    #ENC[AES256_GCM,data:1q9Xj9/w4EbsB3oDOPZ43+Q0HP7WV76zXeIwJVnezkRapP4fJwoL7TOkBzDHNTWeSor0G/N9veOsIQzGv5JTduOMzBxLaD04C70=,iv:VfDwjH07/DB45ZP8x3q0q9ygpYEjfUgByjJBGUmXRMw=,tag:lv6pDkNZE3VFiq3yG2Zuuw==,type:comment]
    password: ENC[AES256_GCM,data:Tkcr1IdzqgtT1XtgsJOAyA==,iv:yKH0It5FkcE7N+ftecWNU9Al5IKVG+iXOuL8KvURdsw=,tag:RCjqGxUSFr/Ulgi1eRNVcQ==,type:str]
    #ENC[AES256_GCM,data:cHYn21cZpPWJA9AG6GHw2jfZwZI4Oh7Qpey/KSL4LNv7AQ71gb7V,iv:XgQJN93pyTQtOrl7oYpnqNVlflJnf7vEWsKQTkjygds=,tag:g8icTCSbnognolB++ebA4w==,type:comment]
    to: ENC[AES256_GCM,data:2pAO9qCyZopyyz3iOc5lGNTcCDQ4,iv:bIl/6VfjE9baaPOXy3pMeJrn2k7fwZLuIOac5pCJMsM=,tag:/0qOh99bkgbbiA5WSdGbiA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOWZxZ0NqdWE2MmJscWhQ
            bFBWRW5QbjZLV2dPeWgrckkwOGdRSVJKN0VrCjNIVlE4eFRNbXVCbW1PVVc3RmZM
            ZzZkM3RUZ2RPNldqWnFKVU9NOFhqYTQKLS0tIG5ESkRxN0pxRVd1TUZsbHdIdFRq
            dFFQL2VFS28rMUlRcWxUdmk1NWVBbkUKwNX8H/5aiZJdlfV4ebE4vQFEb+wHZbPb
            Z65rn9QaeibtySZJ6rFQ1n6M2Px4viBcrk+rOg3CzWkq2G8/Who6CA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1068jmwnqrpg6g2m9aswfwz37fjg7vpwtz5vnxlkcwvf3ed8hjaxsycmf85
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTWlWczhQQUo1VUVTeTZt
            S2RZMEpYb1hvS1Ryak9lNWlKL3Fxb0E0UzFFCkhoZ1kzUlZwMG9xZ0ExUUUvMXhQ
            bVo4TWVFZmd5WGdHWi9oaGhFSGdXMkUKLS0tICt6RUVQWUZZVTVUQmVNOHlNOXJu
            M1huM1BaNzZFb3NJUSs1R2N5aDQxZjAKvV1RFHXUu2eEE1FfeNqmRonZKUoZMgay
            dZ0KdFb5AiUSYcFssm3arjI6xkqGel8qC/87/ztHvLz9KhdZVHpXkg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jmznk7lwandq9d7mm6fq69uwpa7hf79p6h6qztz0e20wj2yw2a8qylelvw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T13:01:18Z"
    mac: ENC[AES256_GCM,data:oCkSeB+42WmrUMsR+HH5HsdqxbCwuBqwmo+VmQYpO+IXMIvtAvILwPWK/yU12oj/U1bhiPs5cc6xzROmPG9rDchepmQUxnDba1omjawhgQiQbLUyV5xohRAtLFCJ9xFzadRtK/TeOHdXKtNFQ4sUuimY3iQkaf3I7whnFmHVvx0=,iv:eYShQg5WVw8dBwRwfAxc2QEJl8ohfCODDtxoRndMCXo=,tag:4dWPD8bai1X001hRo8lvTg==,type:str]
    version: 3.13.2
