apiVersion: v1
kind: Secret
metadata:
    name: wedding-password
stringData:
    password: ENC[AES256_GCM,data:aHHWNs8=,iv:Q4kVS9/s/IZ53usZJA4qZ2YMaggtYpWjF4AKYK3hGTA=,tag:nWA/S2C+fUrxGljO+3+jag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMHZ2S21nRFU0azhjQ2JD
            WGcxYWpOUXRKRzVjTHZnaG01RGRjNUx0MHpNCno1d0JORHZKSlhpY3hjbUNDak1C
            WllBcjNLa1V1TzRaczdFYlpTSmRhWDAKLS0tIFpGcDdjdVpCRmpsWDVOeStsbG5K
            UTlnUFZsL0FRT0d1akxsVmZLbnFSaDAKL/YEHOlugh9khf+y+ICmPCe/YkYnP32t
            3GLrhxHVGD8TXXSDSdrku2k5pVeOXOfT//XbNBZXB4F9I6S16b9z/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1068jmwnqrpg6g2m9aswfwz37fjg7vpwtz5vnxlkcwvf3ed8hjaxsycmf85
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ODYwcG1NOGhsNWpNbXJ5
            dmk4VitrVExFZS8wbGdQWmpDQllWYlVmTUVFCmdtVHFFbEhPcnhDRHh2V1BER01t
            dHdHVy9Fd0t2eCszdi9yOUxYR0lwMU0KLS0tIC92T2dWUjlFRXV4NUVTdHRja2tG
            ZWdDWkR5dlRWeFBGQXoyS3U0bnduVVEKXBZ9mj8H98SmTEyNu53xG9YATJrDBIzS
            BhGT15gwMlR0XJeCW8gHSKGRAUSLSpsW3uxo2JZLFUd9n/U39fk58g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jmznk7lwandq9d7mm6fq69uwpa7hf79p6h6qztz0e20wj2yw2a8qylelvw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T00:31:39Z"
    mac: ENC[AES256_GCM,data:nzCBYWICE6n9r7XEdRLjA5YR0t4B+MCO0AC9alIWuUbjOQjutsWsdEhBT6EH6KtS6dYyv8406ScfLgs9BjNygJRoDpeJipPIDgDw9FVk7OKHyH0yqKbGwh8yrlxm+Ta4GnsWpbZR2nUoGJmDLToy4eUPzUgEFvrlGCgcjhG5YKY=,iv:fDOqgs8J/cycd79GvSA8UeiEtxwmBh3/5ofZ2OoeBHA=,tag:N0OPRm0Yt8oU0qGVZfAXAg==,type:str]
    version: 3.13.1
