# tailscale vpn
- apt:
    pkg:
      - gnupg
- apt_key:
    url: https://pkgs.tailscale.com/stable/debian/{{ ansible_distribution_release }}.noarmor.gpg
    state: present
- apt_repository:
    repo: deb https://pkgs.tailscale.com/stable/debian {{ ansible_distribution_release }} main
    update_cache: yes
- apt:
    pkg:
      - tailscale
- block:
  - command: tailscale status
    # This commands either fails with "Logged out." or succeeds with "Logged in. <...>"
    changed_when: false
  rescue:
  - command: tailscale up --hostname={{ inventory_hostname }} --authkey {{ lookup('env', 'TAILSCALE_AUTH_TOKEN') }} --advertise-exit-node

- command: tailscale ip -4
  register: tailscale_ip
  changed_when: false

- ufw: # allow connections from private ips
    rule: allow
    dest: "{{ tailscale_ip.stdout }}"
