apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: cold
provisioner: ceph.rook.io/block
parameters:
  # # The replicated pool as the `blockPool` parameter
  # blockPool: replicated-metadata-pool
  # The erasure coded pool must be set as the `dataBlockPool` parameter below.
  dataBlockPool: cold
  clusterNamespace: rook-ceph
