- name: Blackhole configuration
  hosts: blackhole

  #####

  # Requirements:
  # - python installed -> `sudo apt-get install -y python3`
  # - passwordless sudo (or pass -K)

  roles:
    - basic
    - docker-debian
    - fileserver-blackhole
    - stash
    # - disk-spindown
