- name: Kubenodes configuration
  hosts: kubenodes
  remote_user: root

  # Requirements:
  # - python installed -> `sudo apt-get install -y python3`
  # - passwordless sudo

  roles:
    - basic
    - tailscale
    - k3s-ingress-nginx
    - k3s-cert-manager
    # - k3s-rook-prerequisites
    - k3s
    - apps
