- name: Kubenodes configuration
  hosts: kubenodes
  remote_user: root

  # Requirements:
  # - python installed -> `sudo apt-get install -y python3`
  # - passwordless sudo

  roles:
    - basic
    - tailscale
    - kubernetes-requirements
    - kubernetes
    - ingress-nginx
    - cert-manager
    #- rook
    #- apps
