apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden
resources:
- namespace.yaml
- statefulset.yaml
- service.yaml
- httpRoute-http.yaml
- httpRoute-https.yaml

- imageRepository.yaml
- imagePolicy.yaml
