apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubelet-csr-approver
spec:
  chart:
    spec:
      chart: kubelet-csr-approver
      sourceRef:
        kind: HelmRepository
        name: kubelet-csr-approver
      version: v1.2.10
  interval: 10m

  valuesFrom:
    - kind: ConfigMap # This value is case sensitive
      name: kubelet-csr-approver-helm-values # automatically overridden by kustomize
      # valuesKey: values.yaml # `values.yaml` is the default key
