apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubelet-csr-approver
resources:
- namespace.yaml
- helmRepository.yaml
- helmRelease.yaml

configMapGenerator:
- name: kubelet-csr-approver-helm-values
  files:
  - values.yaml

configurations:
- kustomizeconfig.yaml # Used to map the generated configmap into the helmRelease
