apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 9.2.3
  interval: 10m

  valuesFrom:
    - kind: ConfigMap # This value is case sensitive
      name: grafana-helm-values # automatically overridden by kustomize
      # valuesKey: values.yaml # `values.yaml` is the default key
