apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  chart:
    spec:
      chart: loki
      version: 9.2.3
      sourceRef:
        kind: HelmRepository
        name: grafana-labs
  interval: 10m

  valuesFrom:
    - kind: ConfigMap # This value is case sensitive
      name: loki-helm-values # automatically overridden by kustomize
      # valuesKey: values.yaml # `values.yaml` is the default key
