apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: thetillhoff
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: thetillhoff
  filterTags:
    pattern: '^v(?P<version>.*)'
    extract: '$version'
  policy:
    semver:
      range: '>=1.0.0'
