name: Destroy deployment

on:
  workflow_dispatch:

jobs:

  delete:
    runs-on: ubuntu-20.04
    steps:
      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_TOKEN }}
      - uses: actions/checkout@v2

      - run: |
          terraform init \
          -input=false
        working-directory: ./terraform

      - run: |
          terraform destroy \
          -auto-approve
        working-directory: ./terraform
        env:
          TF_VAR_KUBENODE_SSH_PRIVATE_KEY: ${{ secrets.KUBENODE_SSH_PRIVATE_KEY }}
          TF_VAR_CLOUDFLARE_EMAIL: ${{ secrets.TF_VAR_CLOUDFLARE_EMAIL }}
          TF_VAR_CLOUDFLARE_APITOKEN: ${{ secrets.TF_VAR_CLOUDFLARE_APITOKEN }}
          TF_VAR_HCLOUD_TOKEN: ${{ secrets.TF_VAR_HCLOUD_TOKEN }}
