name: Destroy

on:
  workflow_dispatch:

jobs:

  delete:
    runs-on: ubuntu-22.04
    steps:
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_TOKEN }}
      - uses: actions/checkout@v3

      - run: |
          terraform init
        working-directory: ./terraform

      - run: |
          terraform  destroy \
          -input=false \
          -auto-approve
        working-directory: ./terraform
        env:
          TF_VAR_CLOUDFLARE_APITOKEN: ${{ secrets.TF_VAR_CLOUDFLARE_APITOKEN }}
          TF_VAR_HCLOUD_TOKEN: ${{ secrets.TF_VAR_HCLOUD_TOKEN }}
