name: Destroy

on:
  workflow_dispatch:

jobs:

  delete:
    runs-on: ubuntu-24.04
    concurrency: terraform-state
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_TOKEN }}
          terraform_version: 1.6.3

      - uses: actions/checkout@v4

      - run: |
          terraform init
        working-directory: ./terraform

      - run: |
          terraform  destroy \
          -input=false \
          -auto-approve
        working-directory: ./terraform
        env:
          TF_VAR_CLOUDFLARE_APITOKEN: ${{ secrets.TF_VAR_CLOUDFLARE_APITOKEN }}
          TF_VAR_HCLOUD_TOKEN: ${{ secrets.TF_VAR_HCLOUD_TOKEN }}
          TF_VAR_HCLOUD_TOKEN_HYDRA: ${{ secrets.TF_VAR_HCLOUD_TOKEN_HYDRA }}
          TF_VAR_GITHUB_TOKEN: ${{ secrets.GH_PAT_FLUX }}
