name: Test

on:
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          pip -V
      - run: |
          ansible-galaxy install -r requirements.yaml
          ansible -v

