name: Test

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:

  set-settings:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - run: |
          gh repo edit thetillhoff/infra -d "Test-description"
        env:
          GH_TOKEN: ${{ github.token }}
