name: Update machine

on:
  schedule:
    - cron: "0 4 3 * *"
  workflow_dispatch:

jobs:

  validate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - run: |
          echo "${{ secrets.KUBENODE_SSH_PRIVATE_KEY }}" > kubenode_ssh.key
          chmod 0400 kubenode_ssh.key
          echo "${{ secrets.KUBENODE_SSH_PUBLIC_KEY }}" > kubenode_ssh.key.pub
          chmod 0400 kubenode_ssh.key.pub

      - run: |
          ansible-galaxy install -r requirements.yaml
        working-directory: ./ansible

      - run: |
          ansible-playbook kubenodes.yaml \
          --inventory ../inventory.ini \
          --verbose \
          --private-key ../kubenode_ssh.key \
          --check
        working-directory: ./ansible
        env:
          TAILSCALE_AUTH_TOKEN: ${{ secrets.TAILSCALE_AUTH_TOKEN }}
          TRANSCRYPT_PASSWORD: ${{ secrets.TRANSCRYPT_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT_FLUX }}
          AGE_KEY: ${{ secrets.AGE_KEY }}
          CLUSTER_NAME: pegasus

  apply:
    needs: validate
    runs-on: ubuntu-24.04
    concurrency: ${{ github.workflow }}-terraform
    steps:
      - uses: actions/checkout@v4

      - run: |
          echo "${{ secrets.KUBENODE_SSH_PRIVATE_KEY }}" > kubenode_ssh.key
          chmod 0400 kubenode_ssh.key
          echo "${{ secrets.KUBENODE_SSH_PUBLIC_KEY }}" > kubenode_ssh.key.pub
          chmod 0400 kubenode_ssh.key.pub

      - run: |
          ansible-galaxy install -r requirements.yaml
        working-directory: ./ansible

      - run: |
          ansible-playbook kubenodes.yaml \
          --inventory inventory.yaml \
          --verbose \
          --private-key ../kubenode_ssh.key
        working-directory: ./ansible
        env:
          TAILSCALE_AUTH_TOKEN: ${{ secrets.TAILSCALE_AUTH_TOKEN }}
          TRANSCRYPT_PASSWORD: ${{ secrets.TRANSCRYPT_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT_FLUX }}
          AGE_KEY: ${{ secrets.AGE_KEY }}
          CLUSTER_NAME: pegasus
